// Ported from faithspark-web/src/constants/data.ts — BOOKS, VERSES (local fallback),
// and SCRIPTURE_FINDER_VERSES only (the rest of that file is prayer-board/games seed
// data not needed by the Bible Reader).

export const BOOKS = [
  { n: "Genesis", c: 50, t: "OT" }, { n: "Exodus", c: 40, t: "OT" }, { n: "Leviticus", c: 27, t: "OT" },
  { n: "Numbers", c: 36, t: "OT" }, { n: "Deuteronomy", c: 34, t: "OT" }, { n: "Joshua", c: 24, t: "OT" },
  { n: "Judges", c: 21, t: "OT" }, { n: "Ruth", c: 4, t: "OT" }, { n: "1 Samuel", c: 31, t: "OT" },
  { n: "2 Samuel", c: 24, t: "OT" }, { n: "1 Kings", c: 22, t: "OT" }, { n: "2 Kings", c: 25, t: "OT" },
  { n: "1 Chronicles", c: 29, t: "OT" }, { n: "2 Chronicles", c: 36, t: "OT" }, { n: "Ezra", c: 10, t: "OT" },
  { n: "Nehemiah", c: 13, t: "OT" }, { n: "Esther", c: 10, t: "OT" }, { n: "Job", c: 42, t: "OT" },
  { n: "Psalms", c: 150, t: "OT" }, { n: "Proverbs", c: 31, t: "OT" }, { n: "Ecclesiastes", c: 12, t: "OT" },
  { n: "Song of Solomon", c: 8, t: "OT" }, { n: "Isaiah", c: 66, t: "OT" }, { n: "Jeremiah", c: 52, t: "OT" },
  { n: "Lamentations", c: 5, t: "OT" }, { n: "Ezekiel", c: 48, t: "OT" }, { n: "Daniel", c: 12, t: "OT" },
  { n: "Hosea", c: 14, t: "OT" }, { n: "Joel", c: 3, t: "OT" }, { n: "Amos", c: 9, t: "OT" },
  { n: "Obadiah", c: 1, t: "OT" }, { n: "Jonah", c: 4, t: "OT" }, { n: "Micah", c: 7, t: "OT" },
  { n: "Nahum", c: 3, t: "OT" }, { n: "Habakkuk", c: 3, t: "OT" }, { n: "Zephaniah", c: 3, t: "OT" },
  { n: "Haggai", c: 2, t: "OT" }, { n: "Zechariah", c: 14, t: "OT" }, { n: "Malachi", c: 4, t: "OT" },
  { n: "Matthew", c: 28, t: "NT" }, { n: "Mark", c: 16, t: "NT" }, { n: "Luke", c: 24, t: "NT" },
  { n: "John", c: 21, t: "NT" }, { n: "Acts", c: 28, t: "NT" }, { n: "Romans", c: 16, t: "NT" },
  { n: "1 Corinthians", c: 16, t: "NT" }, { n: "2 Corinthians", c: 13, t: "NT" }, { n: "Galatians", c: 6, t: "NT" },
  { n: "Ephesians", c: 6, t: "NT" }, { n: "Philippians", c: 4, t: "NT" }, { n: "Colossians", c: 4, t: "NT" },
  { n: "1 Thessalonians", c: 5, t: "NT" }, { n: "2 Thessalonians", c: 3, t: "NT" }, { n: "1 Timothy", c: 6, t: "NT" },
  { n: "2 Timothy", c: 4, t: "NT" }, { n: "Titus", c: 3, t: "NT" }, { n: "Philemon", c: 1, t: "NT" },
  { n: "Hebrews", c: 13, t: "NT" }, { n: "James", c: 5, t: "NT" }, { n: "1 Peter", c: 5, t: "NT" },
  { n: "2 Peter", c: 3, t: "NT" }, { n: "1 John", c: 5, t: "NT" }, { n: "2 John", c: 1, t: "NT" },
  { n: "3 John", c: 1, t: "NT" }, { n: "Jude", c: 1, t: "NT" }, { n: "Revelation", c: 22, t: "NT" },
] as const;

// ─── SAMPLE VERSES (KJV) ──────────────────────────────────────────────────────
export const VERSES: Record<string, { n: number; t: string }[]> = {
  "John-3": [
    { n: 1, t: "There was a man of the Pharisees, named Nicodemus, a ruler of the Jews:" },
    { n: 2, t: "The same came to Jesus by night, and said unto him, Rabbi, we know that thou art a teacher come from God: for no man can do these miracles that thou doest, except God be with him." },
    { n: 3, t: "Jesus answered and said unto him, Verily, verily, I say unto thee, Except a man be born again, he cannot see the kingdom of God." },
    { n: 4, t: "Nicodemus saith unto him, How can a man be born when he is old? can he enter the second time into his mother's womb, and be born?" },
    { n: 5, t: "Jesus answered, Verily, verily, I say unto thee, Except a man be born of water and of the Spirit, he cannot enter into the kingdom of God." },
    { n: 6, t: "That which is born of the flesh is flesh; and that which is born of the Spirit is spirit." },
    { n: 7, t: "Marvel not that I said unto thee, Ye must be born again." },
    { n: 16, t: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life." },
    { n: 17, t: "For God sent not his Son into the world to condemn the world; but that the world through him might be saved." },
    { n: 36, t: "He that believeth on the Son hath everlasting life: and he that believeth not the Son shall not see life; but the wrath of God abideth on him." },
  ],
  "Psalms-23": [
    { n: 1, t: "The LORD is my shepherd; I shall not want." },
    { n: 2, t: "He maketh me to lie down in green pastures: he leadeth me beside the still waters." },
    { n: 3, t: "He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake." },
    { n: 4, t: "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me." },
    { n: 5, t: "Thou preparest a table before me in the presence of mine enemies: thou anointest my head with oil; my cup runneth over." },
    { n: 6, t: "Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the LORD for ever." },
  ],
  "Psalms-1": [
    { n: 1, t: "Blessed is the man that walketh not in the counsel of the ungodly, nor standeth in the way of sinners, nor sitteth in the seat of the scornful." },
    { n: 2, t: "But his delight is in the law of the LORD; and in his law doth he meditate day and night." },
    { n: 3, t: "And he shall be like a tree planted by the rivers of water, that bringeth forth his fruit in his season; his leaf also shall not wither; and whatsoever he doeth shall prosper." },
    { n: 4, t: "The ungodly are not so: but are like the chaff which the wind driveth away." },
    { n: 5, t: "Therefore the ungodly shall not stand in the judgment, nor sinners in the congregation of the righteous." },
    { n: 6, t: "For the LORD knoweth the way of the righteous: but the way of the ungodly shall perish." },
  ],
  "Psalms-91": [
    { n: 1, t: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty." },
    { n: 2, t: "I will say of the LORD, He is my refuge and my fortress: my God; in him will I trust." },
    { n: 3, t: "Surely he shall deliver thee from the snare of the fowler, and from the noisome pestilence." },
    { n: 4, t: "He shall cover thee with his feathers, and under his wings shalt thou trust: his truth shall be thy shield and buckler." },
    { n: 5, t: "Thou shalt not be afraid for the terror by night; nor for the arrow that flieth by day;" },
    { n: 7, t: "A thousand shall fall at thy side, and ten thousand at thy right hand; but it shall not come nigh thee." },
    { n: 9, t: "Because thou hast made the LORD, which is my refuge, even the most High, thy habitation;" },
    { n: 10, t: "There shall no evil befall thee, neither shall any plague come nigh thy dwelling." },
    { n: 11, t: "For he shall give his angels charge over thee, to keep thee in all thy ways." },
    { n: 14, t: "Because he hath set his love upon me, therefore will I deliver him: I will set him on high, because he hath known my name." },
    { n: 15, t: "He shall call upon me, and I will answer him: I will be with him in trouble; I will deliver him, and honour him." },
    { n: 16, t: "With long life will I satisfy him, and shew him my salvation." },
  ],
  "Proverbs-3": [
    { n: 1, t: "My son, forget not my law; but let thine heart keep my commandments:" },
    { n: 2, t: "For length of days, and long life, and peace, shall they add to thee." },
    { n: 3, t: "Let not mercy and truth forsake thee: bind them about thy neck; write them upon the table of thine heart:" },
    { n: 4, t: "So shalt thou find favour and good understanding in the sight of God and man." },
    { n: 5, t: "Trust in the LORD with all thine heart; and lean not unto thine own understanding." },
    { n: 6, t: "In all thy ways acknowledge him, and he shall direct thy paths." },
    { n: 7, t: "Be not wise in thine own eyes: fear the LORD, and depart from evil." },
    { n: 8, t: "It shall be health to thy navel, and marrow to thy bones." },
    { n: 9, t: "Honour the LORD with thy substance, and with the firstfruits of all thine increase:" },
    { n: 10, t: "So shall thy barns be filled with plenty, and thy presses shall burst out with new wine." },
  ],
  "Isaiah-40": [
    { n: 1, t: "Comfort ye, comfort ye my people, saith your God." },
    { n: 3, t: "The voice of him that crieth in the wilderness, Prepare ye the way of the LORD, make straight in the desert a highway for our God." },
    { n: 8, t: "The grass withereth, the flower fadeth: but the word of our God shall stand for ever." },
    { n: 11, t: "He shall feed his flock like a shepherd: he shall gather the lambs with his arm, and carry them in his bosom, and shall gently lead those that are with young." },
    { n: 28, t: "Hast thou not known? hast thou not heard, that the everlasting God, the LORD, the Creator of the ends of the earth, fainteth not, neither is weary? there is no searching of his understanding." },
    { n: 29, t: "He giveth power to the faint; and to them that have no might he increaseth strength." },
    { n: 30, t: "Even the youths shall faint and be weary, and the young men shall utterly fall:" },
    { n: 31, t: "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint." },
  ],
  "Matthew-5": [
    { n: 3, t: "Blessed are the poor in spirit: for theirs is the kingdom of heaven." },
    { n: 4, t: "Blessed are they that mourn: for they shall be comforted." },
    { n: 5, t: "Blessed are the meek: for they shall inherit the earth." },
    { n: 6, t: "Blessed are they which do hunger and thirst after righteousness: for they shall be filled." },
    { n: 7, t: "Blessed are the merciful: for they shall obtain mercy." },
    { n: 8, t: "Blessed are the pure in heart: for they shall see God." },
    { n: 9, t: "Blessed are the peacemakers: for they shall be called the children of God." },
    { n: 10, t: "Blessed are they which are persecuted for righteousness' sake: for theirs is the kingdom of heaven." },
    { n: 14, t: "Ye are the light of the world. A city that is set on an hill cannot be hid." },
    { n: 16, t: "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven." },
    { n: 44, t: "But I say unto you, Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you;" },
    { n: 48, t: "Be ye therefore perfect, even as your Father which is in heaven is perfect." },
  ],
  "Romans-8": [
    { n: 1, t: "There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but after the Spirit." },
    { n: 11, t: "But if the Spirit of him that raised up Jesus from the dead dwell in you, he that raised up Christ from the dead shall also quicken your mortal bodies by his Spirit that dwelleth in you." },
    { n: 16, t: "The Spirit itself beareth witness with our spirit, that we are the children of God:" },
    { n: 17, t: "And if children, then heirs; heirs of God, and joint-heirs with Christ; if so be that we suffer with him, that we may be also glorified together." },
    { n: 18, t: "For I reckon that the sufferings of this present time are not worthy to be compared with the glory which shall be revealed in us." },
    { n: 26, t: "Likewise the Spirit also helpeth our infirmities: for we know not what we should pray for as we ought: but the Spirit itself maketh intercession for us with groanings which cannot be uttered." },
    { n: 28, t: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose." },
    { n: 31, t: "What shall we then say to these things? If God be for us, who can be against us?" },
    { n: 37, t: "Nay, in all these things we are more than conquerors through him that loved us." },
    { n: 38, t: "For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come," },
    { n: 39, t: "Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord." },
  ],
  "John-1": [
    { n: 1, t: "In the beginning was the Word, and the Word was with God, and the Word was God." },
    { n: 2, t: "The same was in the beginning with God." },
    { n: 3, t: "All things were made by him; and without him was not any thing made that was made." },
    { n: 4, t: "In him was life; and the life was the light of men." },
    { n: 5, t: "And the light shineth in darkness; and the darkness comprehended it not." },
    { n: 12, t: "But as many as received him, to them gave he power to become the sons of God, even to them that believe on his name:" },
    { n: 14, t: "And the Word was made flesh, and dwelt among us, (and we beheld his glory, the glory as of the only begotten of the Father,) full of grace and truth." },
    { n: 29, t: "The next day John seeth Jesus coming unto him, and saith, Behold the Lamb of God, which taketh away the sin of the world." },
  ],
  "Genesis-1": [
    { n: 1, t: "In the beginning God created the heaven and the earth." },
    { n: 2, t: "And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters." },
    { n: 3, t: "And God said, Let there be light: and there was light." },
    { n: 4, t: "And God saw the light, that it was good: and God divided the light from the darkness." },
    { n: 26, t: "And God said, Let us make man in our image, after our likeness: and let them have dominion over the fish of the sea, and over the fowl of the air, and over the cattle, and over all the earth." },
    { n: 27, t: "So God created man in his own image, in the image of God created he him; male and female created he them." },
    { n: 28, t: "And God blessed them, and God said unto them, Be fruitful, and multiply, and replenish the earth, and subdue it." },
    { n: 31, t: "And God saw every thing that he had made, and, behold, it was very good. And the evening and the morning were the sixth day." },
  ],
  "1 Corinthians-13": [
    { n: 1, t: "Though I speak with the tongues of men and of angels, and have not charity, I am become as sounding brass, or a tinkling cymbal." },
    { n: 2, t: "And though I have the gift of prophecy, and understand all mysteries, and all knowledge; and though I have all faith, so that I could remove mountains, and have not charity, I am nothing." },
    { n: 3, t: "And though I bestow all my goods to feed the poor, and though I give my body to be burned, and have not charity, it profiteth me nothing." },
    { n: 4, t: "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up," },
    { n: 5, t: "Doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil;" },
    { n: 6, t: "Rejoiceth not in iniquity, but rejoiceth in the truth;" },
    { n: 7, t: "Beareth all things, believeth all things, hopeth all things, endureth all things." },
    { n: 8, t: "Charity never faileth: but whether there be prophecies, they shall fail; whether there be tongues, they shall cease; whether there be knowledge, it shall vanish away." },
    { n: 11, t: "When I was a child, I spake as a child, I understood as a child, I thought as a child: but when I became a man, I put away childish things." },
    { n: 12, t: "For now we see through a glass, darkly; but then face to face: now I know in part; but then shall I know even as also I am known." },
    { n: 13, t: "And now abideth faith, hope, charity, these three; but the greatest of these is charity." },
  ],
  "Philippians-4": [
    { n: 4, t: "Rejoice in the Lord alway: and again I say, Rejoice." },
    { n: 5, t: "Let your moderation be known unto all men. The Lord is at hand." },
    { n: 6, t: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God." },
    { n: 7, t: "And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus." },
    { n: 8, t: "Finally, brethren, whatsoever things are true, whatsoever things are honest, whatsoever things are just, whatsoever things are pure, whatsoever things are lovely, whatsoever things are of good report; if there be any virtue, and if there be any praise, think on these things." },
    { n: 11, t: "Not that I speak in respect of want: for I have learned, in whatsoever state I am, therewith to be content." },
    { n: 13, t: "I can do all things through Christ which strengtheneth me." },
    { n: 19, t: "But my God shall supply all your need according to his riches in glory by Christ Jesus." },
  ],
  "Hebrews-11": [
    { n: 1, t: "Now faith is the substance of things hoped for, the evidence of things not seen." },
    { n: 2, t: "For by it the elders obtained a good report." },
    { n: 3, t: "Through faith we understand that the worlds were framed by the word of God, so that things which are seen were not made of things which do appear." },
    { n: 6, t: "But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him." },
    { n: 8, t: "By faith Abraham, when he was called to go out into a place which he should after receive for an inheritance, obeyed; and he went out, not knowing whither he went." },
    { n: 33, t: "Who through faith subdued kingdoms, wrought righteousness, obtained promises, stopped the mouths of lions," },
    { n: 39, t: "And these all, having obtained a good report through faith, received not the promise:" },
    { n: 40, t: "God having provided some better thing for us, that they without us should not be made perfect." },
  ],
  "Jeremiah-29": [
    { n: 11, t: "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end." },
    { n: 12, t: "Then shall ye call upon me, and ye shall go and pray unto me, and I will hearken unto you." },
    { n: 13, t: "And ye shall seek me, and find me, when ye shall search for me with all your heart." },
  ],
  "Romans-12": [
    { n: 1, t: "I beseech you therefore, brethren, by the mercies of God, that ye present your bodies a living sacrifice, holy, acceptable unto God, which is your reasonable service." },
    { n: 2, t: "And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God." },
    { n: 9, t: "Let love be without dissimulation. Abhor that which is evil; cleave to that which is good." },
    { n: 10, t: "Be kindly affectioned one to another with brotherly love; in honour preferring one another;" },
    { n: 12, t: "Rejoicing in hope; patient in tribulation; continuing instant in prayer;" },
    { n: 16, t: "Be of the same mind one toward another. Mind not high things, but condescend to men of low estate. Be not wise in your own conceits." },
    { n: 21, t: "Be not overcome of evil, but overcome evil with good." },
  ],
};

export type ScriptureFinderVerse = {
  ref: string;
  text: string;
  book: string;
  chapter: number;
  topics: string[];
};

export const SCRIPTURE_FINDER_VERSES: ScriptureFinderVerse[] = [
  // ── John ──
  { ref: "John 3:16", book: "John", chapter: 3, topics: ["love","salvation","Jesus","God","heaven"], text: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life." },
  { ref: "John 14:6", book: "John", chapter: 14, topics: ["Jesus","salvation","truth","faith"], text: "Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me." },
  { ref: "John 14:27", book: "John", chapter: 14, topics: ["peace","fear","Jesus"], text: "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid." },
  { ref: "John 16:33", book: "John", chapter: 16, topics: ["peace","suffering","Jesus","strength"], text: "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world." },
  { ref: "John 15:13", book: "John", chapter: 15, topics: ["love","Jesus","sacrifice"], text: "Greater love hath no man than this, that a man lay down his life for his friends." },
  { ref: "John 13:34", book: "John", chapter: 13, topics: ["love","obedience","Jesus"], text: "A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another." },
  { ref: "John 8:32", book: "John", chapter: 8, topics: ["truth","freedom","Jesus"], text: "And ye shall know the truth, and the truth shall make you free." },
  { ref: "John 10:10", book: "John", chapter: 10, topics: ["Jesus","purpose","life"], text: "The thief cometh not, but for to steal, and to kill, and to destroy: I am come that they might have life, and that they might have it more abundantly." },
  { ref: "John 1:1", book: "John", chapter: 1, topics: ["Jesus","God","creation"], text: "In the beginning was the Word, and the Word was with God, and the Word was God." },
  { ref: "John 11:35", book: "John", chapter: 11, topics: ["Jesus","suffering","compassion"], text: "Jesus wept." },
  { ref: "John 15:5", book: "John", chapter: 15, topics: ["Jesus","faith","obedience"], text: "I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit: for without me ye can do nothing." },
  { ref: "John 4:24", book: "John", chapter: 4, topics: ["worship","God","Holy Spirit"], text: "God is a Spirit: and they that worship him must worship him in spirit and in truth." },
  { ref: "John 10:27", book: "John", chapter: 10, topics: ["Jesus","obedience","trust"], text: "My sheep hear my voice, and I know them, and they follow me: And I give unto them eternal life; and they shall never perish." },
  { ref: "John 6:35", book: "John", chapter: 6, topics: ["Jesus","faith","salvation"], text: "And Jesus said unto them, I am the bread of life: he that cometh to me shall never hunger; and he that believeth on me shall never thirst." },
  { ref: "John 17:17", book: "John", chapter: 17, topics: ["truth","sanctification"], text: "Sanctify them through thy truth: thy word is truth." },
  // ── Psalms ──
  { ref: "Psalm 23:1", book: "Psalms", chapter: 23, topics: ["trust","God","peace"], text: "The LORD is my shepherd; I shall not want." },
  { ref: "Psalm 23:4", book: "Psalms", chapter: 23, topics: ["fear","death","God","trust"], text: "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me." },
  { ref: "Psalm 46:10", book: "Psalms", chapter: 46, topics: ["peace","God","worship"], text: "Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth." },
  { ref: "Psalm 46:1", book: "Psalms", chapter: 46, topics: ["strength","trust","God","suffering"], text: "God is our refuge and strength, a very present help in trouble." },
  { ref: "Psalm 119:105", book: "Psalms", chapter: 119, topics: ["wisdom","obedience","purpose"], text: "Thy word is a lamp unto my feet, and a light unto my path." },
  { ref: "Psalm 91:1", book: "Psalms", chapter: 91, topics: ["God","trust","peace","protection"], text: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty." },
  { ref: "Psalm 91:4", book: "Psalms", chapter: 91, topics: ["trust","God","protection","faith"], text: "He shall cover thee with his feathers, and under his wings shalt thou trust: his truth shall be thy shield and buckler." },
  { ref: "Psalm 91:11", book: "Psalms", chapter: 91, topics: ["God","protection","angels"], text: "For he shall give his angels charge over thee, to keep thee in all thy ways." },
  { ref: "Psalm 27:1", book: "Psalms", chapter: 27, topics: ["fear","strength","God","salvation"], text: "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?" },
  { ref: "Psalm 27:14", book: "Psalms", chapter: 27, topics: ["hope","strength","trust","God"], text: "Wait on the LORD: be of good courage, and he shall strengthen thine heart: wait, I say, on the LORD." },
  { ref: "Psalm 37:4", book: "Psalms", chapter: 37, topics: ["joy","trust","God","purpose"], text: "Delight thyself also in the LORD; and he shall give thee the desires of thine heart." },
  { ref: "Psalm 37:5", book: "Psalms", chapter: 37, topics: ["trust","obedience","God"], text: "Commit thy way unto the LORD; trust also in him; and he shall bring it to pass." },
  { ref: "Psalm 55:22", book: "Psalms", chapter: 55, topics: ["worry","trust","God","suffering"], text: "Cast thy burden upon the LORD, and he shall sustain thee: he shall never suffer the righteous to be moved." },
  { ref: "Psalm 139:14", book: "Psalms", chapter: 139, topics: ["creation","purpose","worship","God"], text: "I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well." },
  { ref: "Psalm 139:1", book: "Psalms", chapter: 139, topics: ["God","purpose","creation"], text: "O LORD, thou hast searched me, and known me. Thou knowest my downsitting and mine uprising, thou understandest my thought afar off." },
  { ref: "Psalm 34:18", book: "Psalms", chapter: 34, topics: ["God","suffering","healing","hope"], text: "The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit." },
  { ref: "Psalm 34:8", book: "Psalms", chapter: 34, topics: ["trust","joy","God"], text: "O taste and see that the LORD is good: blessed is the man that trusteth in him." },
  { ref: "Psalm 103:12", book: "Psalms", chapter: 103, topics: ["forgiveness","grace","God","sin"], text: "As far as the east is from the west, so far hath he removed our transgressions from us." },
  { ref: "Psalm 118:24", book: "Psalms", chapter: 118, topics: ["joy","worship","God"], text: "This is the day which the LORD hath made; we will rejoice and be glad in it." },
  { ref: "Psalm 121:1", book: "Psalms", chapter: 121, topics: ["God","trust","creation","help"], text: "I will lift up mine eyes unto the hills, from whence cometh my help. My help cometh from the LORD, which made heaven and earth." },
  { ref: "Psalm 51:10", book: "Psalms", chapter: 51, topics: ["sin","forgiveness","Holy Spirit","renewal"], text: "Create in me a clean heart, O God; and renew a right spirit within me." },
  { ref: "Psalm 16:11", book: "Psalms", chapter: 16, topics: ["joy","heaven","God","purpose"], text: "Thou wilt shew me the path of life: in thy presence is fulness of joy; at thy right hand there are pleasures for evermore." },
  { ref: "Psalm 30:5", book: "Psalms", chapter: 30, topics: ["suffering","joy","hope","God"], text: "For his anger endureth but a moment; in his favour is life: weeping may endure for a night, but joy cometh in the morning." },
  { ref: "Psalm 56:3", book: "Psalms", chapter: 56, topics: ["fear","trust","God"], text: "What time I am afraid, I will trust in thee." },
  { ref: "Psalm 62:8", book: "Psalms", chapter: 62, topics: ["trust","prayer","God","suffering"], text: "Trust in him at all times; ye people, pour out your heart before him: God is a refuge for us." },
  { ref: "Psalm 73:26", book: "Psalms", chapter: 73, topics: ["strength","God","trust","suffering"], text: "My flesh and my heart faileth: but God is the strength of my heart, and my portion for ever." },
  { ref: "Psalm 84:11", book: "Psalms", chapter: 84, topics: ["grace","God","obedience","trust"], text: "For the LORD God is a sun and shield: the LORD will give grace and glory: no good thing will he withhold from them that walk uprightly." },
  { ref: "Psalm 86:5", book: "Psalms", chapter: 86, topics: ["forgiveness","grace","prayer","God"], text: "For thou, Lord, art good, and ready to forgive; and plenteous in mercy unto all them that call upon thee." },
  { ref: "Psalm 100:4", book: "Psalms", chapter: 100, topics: ["worship","joy","God","thanksgiving"], text: "Enter into his gates with thanksgiving, and into his courts with praise: be thankful unto him, and bless his name." },
  { ref: "Psalm 107:1", book: "Psalms", chapter: 107, topics: ["worship","God","grace","thanksgiving"], text: "O give thanks unto the LORD, for he is good: for his mercy endureth for ever." },
  { ref: "Psalm 111:10", book: "Psalms", chapter: 111, topics: ["wisdom","fear","obedience","God"], text: "The fear of the LORD is the beginning of wisdom: a good understanding have all they that do his commandments: his praise endureth for ever." },
  { ref: "Psalm 119:11", book: "Psalms", chapter: 119, topics: ["sin","obedience","wisdom"], text: "Thy word have I hid in mine heart, that I might not sin against thee." },
  { ref: "Psalm 126:5", book: "Psalms", chapter: 126, topics: ["suffering","joy","hope"], text: "They that sow in tears shall reap in joy." },
  { ref: "Psalm 145:18", book: "Psalms", chapter: 145, topics: ["prayer","God","trust"], text: "The LORD is nigh unto all them that call upon him, to all that call upon him in truth." },
  { ref: "Psalm 150:6", book: "Psalms", chapter: 150, topics: ["worship","praise","God"], text: "Let every thing that hath breath praise the LORD. Praise ye the LORD." },
  { ref: "Psalm 19:14", book: "Psalms", chapter: 19, topics: ["worship","prayer","God"], text: "Let the words of my mouth, and the meditation of my heart, be acceptable in thy sight, O LORD, my strength, and my redeemer." },
  { ref: "Psalm 25:4", book: "Psalms", chapter: 25, topics: ["obedience","wisdom","trust","salvation"], text: "Shew me thy ways, O LORD; teach me thy paths. Lead me in thy truth, and teach me: for thou art the God of my salvation; on thee do I wait all the day." },
  { ref: "Psalm 28:7", book: "Psalms", chapter: 28, topics: ["strength","trust","worship","God"], text: "The LORD is my strength and my shield; my heart trusted in him, and I am helped: therefore my heart greatly rejoiceth; and with my song will I praise him." },
  { ref: "Psalm 29:11", book: "Psalms", chapter: 29, topics: ["strength","peace","God"], text: "The LORD will give strength unto his people; the LORD will bless his people with peace." },
  { ref: "Psalm 31:24", book: "Psalms", chapter: 31, topics: ["hope","strength","courage"], text: "Be of good courage, and he shall strengthen your heart, all ye that hope in the LORD." },
  { ref: "Psalm 40:3", book: "Psalms", chapter: 40, topics: ["worship","trust","God","joy"], text: "And he hath put a new song in my mouth, even praise unto our God: many shall see it, and fear, and shall trust in the LORD." },
  { ref: "Psalm 42:11", book: "Psalms", chapter: 42, topics: ["hope","suffering","God","praise"], text: "Why art thou cast down, O my soul? and why art thou disquieted within me? hope thou in God: for I shall yet praise him, who is the health of my countenance, and my God." },
  { ref: "Psalm 9:9", book: "Psalms", chapter: 9, topics: ["God","suffering","trust","protection"], text: "The LORD also will be a refuge for the oppressed, a refuge in times of trouble." },
  { ref: "Psalm 4:8", book: "Psalms", chapter: 4, topics: ["peace","trust","God"], text: "I will both lay me down in peace, and sleep: for thou, LORD, only makest me dwell in safety." },
  { ref: "Psalm 33:4", book: "Psalms", chapter: 33, topics: ["truth","God","trust"], text: "For the word of the LORD is right; and all his works are done in truth." },
  { ref: "Psalm 5:3", book: "Psalms", chapter: 5, topics: ["prayer","worship","God"], text: "My voice shalt thou hear in the morning, O LORD; in the morning will I direct my prayer unto thee, and will look up." },
  { ref: "Psalm 18:2", book: "Psalms", chapter: 18, topics: ["strength","God","trust","salvation"], text: "The LORD is my rock, and my fortress, and my deliverer; my God, my strength, in whom I will trust; my buckler, and the horn of my salvation, and my high tower." },
  { ref: "Psalm 32:8", book: "Psalms", chapter: 32, topics: ["wisdom","obedience","God","guidance"], text: "I will instruct thee and teach thee in the way which thou shalt go: I will guide thee with mine eye." },
  { ref: "Psalm 37:7", book: "Psalms", chapter: 37, topics: ["trust","patience","hope","God"], text: "Rest in the LORD, and wait patiently for him: fret not thyself because of him who prospereth in his way, because of the man who bringeth wicked devices to pass." },
  { ref: "Psalm 50:15", book: "Psalms", chapter: 50, topics: ["prayer","God","suffering","trust"], text: "And call upon me in the day of trouble: I will deliver thee, and thou shalt glorify me." },
  { ref: "Psalm 66:19", book: "Psalms", chapter: 66, topics: ["prayer","God","trust"], text: "But verily God hath heard me; he hath attended to the voice of my prayer." },
  { ref: "Psalm 68:19", book: "Psalms", chapter: 68, topics: ["God","trust","praise"], text: "Blessed be the Lord, who daily loadeth us with benefits, even the God of our salvation." },
  { ref: "Psalm 90:12", book: "Psalms", chapter: 90, topics: ["wisdom","purpose","life"], text: "So teach us to number our days, that we may apply our hearts unto wisdom." },
  { ref: "Psalm 91:2", book: "Psalms", chapter: 91, topics: ["trust","God","protection"], text: "I will say of the LORD, He is my refuge and my fortress: my God; in him will I trust." },
  { ref: "Psalm 103:2", book: "Psalms", chapter: 103, topics: ["worship","God","grace","healing"], text: "Bless the LORD, O my soul, and forget not all his benefits: Who forgiveth all thine iniquities; who healeth all thy diseases." },
  { ref: "Psalm 106:1", book: "Psalms", chapter: 106, topics: ["worship","God","grace","thanksgiving"], text: "Praise ye the LORD. O give thanks unto the LORD; for he is good: for his mercy endureth for ever." },
  { ref: "Psalm 133:1", book: "Psalms", chapter: 133, topics: ["family","unity","love"], text: "Behold, how good and how pleasant it is for brethren to dwell together in unity!" },
  { ref: "Psalm 138:8", book: "Psalms", chapter: 138, topics: ["purpose","God","trust","hope"], text: "The LORD will perfect that which concerneth me: thy mercy, O LORD, endureth for ever: forsake not the works of thine own hands." },
  { ref: "Psalm 147:3", book: "Psalms", chapter: 147, topics: ["healing","God","suffering","hope"], text: "He healeth the broken in heart, and bindeth up their wounds." },
  // ── Proverbs ──
  { ref: "Proverbs 3:5", book: "Proverbs", chapter: 3, topics: ["trust","faith","wisdom","obedience"], text: "Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths." },
  { ref: "Proverbs 4:23", book: "Proverbs", chapter: 4, topics: ["wisdom","sin","obedience"], text: "Keep thy heart with all diligence; for out of it are the issues of life." },
  { ref: "Proverbs 15:1", book: "Proverbs", chapter: 15, topics: ["anger","wisdom","enemies"], text: "A soft answer turneth away wrath: but grievous words stir up anger." },
  { ref: "Proverbs 16:9", book: "Proverbs", chapter: 16, topics: ["purpose","God","trust","wisdom"], text: "A man's heart deviseth his way: but the LORD directeth his steps." },
  { ref: "Proverbs 17:17", book: "Proverbs", chapter: 17, topics: ["love","family","suffering"], text: "A friend loveth at all times, and a brother is born for adversity." },
  { ref: "Proverbs 18:10", book: "Proverbs", chapter: 18, topics: ["strength","God","trust","salvation"], text: "The name of the LORD is a strong tower: the righteous runneth into it, and is safe." },
  { ref: "Proverbs 22:6", book: "Proverbs", chapter: 22, topics: ["children","family","obedience"], text: "Train up a child in the way he should go: and when he is old, he will not depart from it." },
  { ref: "Proverbs 29:18", book: "Proverbs", chapter: 29, topics: ["purpose","obedience","wisdom"], text: "Where there is no vision, the people perish: but he that keepeth the law, happy is he." },
  { ref: "Proverbs 31:25", book: "Proverbs", chapter: 31, topics: ["strength","women","joy","purpose"], text: "Strength and honour are her clothing; and she shall rejoice in time to come." },
  { ref: "Proverbs 10:22", book: "Proverbs", chapter: 10, topics: ["money","God","blessing"], text: "The blessing of the LORD, it maketh rich, and he addeth no sorrow with it." },
  { ref: "Proverbs 11:14", book: "Proverbs", chapter: 11, topics: ["wisdom","community"], text: "Where no counsel is, the people fall: but in the multitude of counsellors there is safety." },
  { ref: "Proverbs 13:20", book: "Proverbs", chapter: 13, topics: ["wisdom","community","obedience"], text: "He that walketh with wise men shall be wise: but a companion of fools shall be destroyed." },
  { ref: "Proverbs 19:21", book: "Proverbs", chapter: 19, topics: ["purpose","God","wisdom","trust"], text: "There are many devices in a man's heart; nevertheless the counsel of the LORD, that shall stand." },
  { ref: "Proverbs 23:7", book: "Proverbs", chapter: 23, topics: ["wisdom","mind"], text: "For as he thinketh in his heart, so is he." },
  { ref: "Proverbs 27:1", book: "Proverbs", chapter: 27, topics: ["pride","worry","humility","wisdom"], text: "Boast not thyself of to morrow; for thou knowest not what a day may bring forth." },
  { ref: "Proverbs 1:7", book: "Proverbs", chapter: 1, topics: ["wisdom","God","obedience"], text: "The fear of the LORD is the beginning of knowledge: but fools despise wisdom and instruction." },
  { ref: "Proverbs 3:6", book: "Proverbs", chapter: 3, topics: ["obedience","purpose","God","guidance"], text: "In all thy ways acknowledge him, and he shall direct thy paths." },
  { ref: "Proverbs 4:7", book: "Proverbs", chapter: 4, topics: ["wisdom","obedience"], text: "Wisdom is the principal thing; therefore get wisdom: and with all thy getting get understanding." },
  { ref: "Proverbs 10:12", book: "Proverbs", chapter: 10, topics: ["love","anger","hate"], text: "Hatred stirreth up strifes: but love covereth all sins." },
  { ref: "Proverbs 11:2", book: "Proverbs", chapter: 11, topics: ["pride","humility","wisdom"], text: "When pride cometh, then cometh shame: but with the lowly is wisdom." },
  { ref: "Proverbs 12:1", book: "Proverbs", chapter: 12, topics: ["wisdom","obedience","work"], text: "Whoso loveth instruction loveth knowledge: but he that hateth reproof is brutish." },
  { ref: "Proverbs 14:12", book: "Proverbs", chapter: 14, topics: ["wisdom","sin","obedience"], text: "There is a way which seemeth right unto a man, but the end thereof are the ways of death." },
  { ref: "Proverbs 16:3", book: "Proverbs", chapter: 16, topics: ["purpose","work","trust","God"], text: "Commit thy works unto the LORD, and thy thoughts shall be established." },
  { ref: "Proverbs 16:18", book: "Proverbs", chapter: 16, topics: ["pride","sin","humility"], text: "Pride goeth before destruction, and an haughty spirit before a fall." },
  { ref: "Proverbs 18:21", book: "Proverbs", chapter: 18, topics: ["wisdom","sin","obedience"], text: "Death and life are in the power of the tongue: and they that love it shall eat the fruit thereof." },
  { ref: "Proverbs 22:7", book: "Proverbs", chapter: 22, topics: ["money","work","obedience"], text: "The rich ruleth over the poor, and the borrower is servant to the lender." },
  { ref: "Proverbs 25:11", book: "Proverbs", chapter: 25, topics: ["wisdom","love"], text: "A word fitly spoken is like apples of gold in pictures of silver." },
  { ref: "Proverbs 31:10", book: "Proverbs", chapter: 31, topics: ["marriage","women","family"], text: "Who can find a virtuous woman? for her price is far above rubies." },
  // ── Isaiah ──
  { ref: "Isaiah 40:31", book: "Isaiah", chapter: 40, topics: ["strength","hope","trust","God"], text: "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint." },
  { ref: "Isaiah 41:10", book: "Isaiah", chapter: 41, topics: ["fear","strength","God","trust"], text: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness." },
  { ref: "Isaiah 53:5", book: "Isaiah", chapter: 53, topics: ["healing","salvation","sin","Jesus"], text: "But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed." },
  { ref: "Isaiah 26:3", book: "Isaiah", chapter: 26, topics: ["peace","trust","God","worry"], text: "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee." },
  { ref: "Isaiah 43:2", book: "Isaiah", chapter: 43, topics: ["suffering","God","trust","fear"], text: "When thou passest through the waters, I will be with thee; and through the rivers, they shall not overflow thee: when thou walkest through the fire, thou shalt not be burned; neither shall the flame kindle upon thee." },
  { ref: "Isaiah 43:19", book: "Isaiah", chapter: 43, topics: ["hope","purpose","God","renewal"], text: "Behold, I will do a new thing; now it shall spring forth; shall ye not know it? I will even make a way in the wilderness, and rivers in the desert." },
  { ref: "Isaiah 54:17", book: "Isaiah", chapter: 54, topics: ["enemies","God","protection","faith"], text: "No weapon that is formed against thee shall prosper; and every tongue that shall rise against thee in judgment thou shalt condemn. This is the heritage of the servants of the LORD." },
  { ref: "Isaiah 55:8", book: "Isaiah", chapter: 55, topics: ["God","wisdom","trust"], text: "For my thoughts are not your thoughts, neither are your ways my ways, saith the LORD." },
  { ref: "Isaiah 9:6", book: "Isaiah", chapter: 9, topics: ["Jesus","peace","God","salvation"], text: "For unto us a child is born, unto us a son is given: and the government shall be upon his shoulder: and his name shall be called Wonderful, Counsellor, The mighty God, The everlasting Father, The Prince of Peace." },
  { ref: "Isaiah 64:8", book: "Isaiah", chapter: 64, topics: ["God","creation","purpose"], text: "But now, O LORD, thou art our father; we are the clay, and thou our potter; and we all are the work of thy hand." },
  { ref: "Isaiah 40:28", book: "Isaiah", chapter: 40, topics: ["God","strength","creation","wisdom"], text: "Hast thou not known? hast thou not heard, that the everlasting God, the LORD, the Creator of the ends of the earth, fainteth not, neither is weary? there is no searching of his understanding." },
  { ref: "Isaiah 43:1", book: "Isaiah", chapter: 43, topics: ["God","fear","salvation","love"], text: "But now thus saith the LORD that created thee, O Jacob, and he that formed thee, O Israel, Fear not: for I have redeemed thee, I have called thee by thy name; thou art mine." },
  { ref: "Isaiah 48:17", book: "Isaiah", chapter: 48, topics: ["God","wisdom","obedience","guidance"], text: "Thus saith the LORD, thy Redeemer, the Holy One of Israel; I am the LORD thy God which teacheth thee to profit, which leadeth thee by the way that thou shouldest go." },
  { ref: "Isaiah 58:11", book: "Isaiah", chapter: 58, topics: ["God","guidance","healing","purpose"], text: "And the LORD shall guide thee continually, and satisfy thy soul in drought, and make fat thy bones: and thou shalt be like a watered garden." },
  // ── Jeremiah ──
  { ref: "Jeremiah 29:11", book: "Jeremiah", chapter: 29, topics: ["purpose","hope","God","peace"], text: "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end." },
  { ref: "Jeremiah 33:3", book: "Jeremiah", chapter: 33, topics: ["prayer","God","wisdom","trust"], text: "Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not." },
  { ref: "Jeremiah 17:14", book: "Jeremiah", chapter: 17, topics: ["healing","salvation","God","prayer"], text: "Heal me, O LORD, and I shall be healed; save me, and I shall be saved: for thou art my praise." },
  { ref: "Jeremiah 17:9", book: "Jeremiah", chapter: 17, topics: ["sin","heart","wisdom"], text: "The heart is deceitful above all things, and desperately wicked: who can know it?" },
  { ref: "Jeremiah 31:3", book: "Jeremiah", chapter: 31, topics: ["love","God","grace"], text: "The LORD hath appeared of old unto me, saying, Yea, I have loved thee with an everlasting love; therefore with lovingkindness have I drawn thee." },
  // ── Lamentations ──
  { ref: "Lamentations 3:22", book: "Lamentations", chapter: 3, topics: ["grace","mercy","God","hope"], text: "It is of the LORD's mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness." },
  { ref: "Lamentations 3:25", book: "Lamentations", chapter: 3, topics: ["hope","God","trust","patience"], text: "The LORD is good unto them that wait for him, to the soul that seeketh him." },
  // ── Ezekiel ──
  { ref: "Ezekiel 36:26", book: "Ezekiel", chapter: 36, topics: ["renewal","Holy Spirit","heart","sin"], text: "A new heart also will I give you, and a new spirit will I put within you: and I will take away the stony heart out of your flesh, and I will give you an heart of flesh." },
  // ── Daniel ──
  { ref: "Daniel 3:17", book: "Daniel", chapter: 3, topics: ["faith","God","suffering","trust"], text: "If it be so, our God whom we serve is able to deliver us from the burning fiery furnace, and he will deliver us out of thine hand, O king." },
  { ref: "Daniel 6:22", book: "Daniel", chapter: 6, topics: ["God","faith","protection","trust"], text: "My God hath sent his angel, and hath shut the lions' mouths, that they have not hurt me: forasmuch as before him innocency was found in me." },
  // ── Hosea ──
  { ref: "Hosea 6:6", book: "Hosea", chapter: 6, topics: ["mercy","obedience","worship","God"], text: "For I desired mercy, and not sacrifice; and the knowledge of God more than burnt offerings." },
  // ── Joel ──
  { ref: "Joel 2:25", book: "Joel", chapter: 2, topics: ["healing","hope","God","restoration"], text: "And I will restore to you the years that the locust hath eaten, the cankerworm, and the caterpiller, and the palmerworm, my great army which I sent among you." },
  { ref: "Joel 2:28", book: "Joel", chapter: 2, topics: ["Holy Spirit","prophecy","God"], text: "And it shall come to pass afterward, that I will pour out my spirit upon all flesh; and your sons and your daughters shall prophesy, your old men shall dream dreams, your young men shall see visions:" },
  // ── Micah ──
  { ref: "Micah 6:8", book: "Micah", chapter: 6, topics: ["obedience","humility","love","God"], text: "He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?" },
  // ── Nahum ──
  { ref: "Nahum 1:7", book: "Nahum", chapter: 1, topics: ["God","trust","suffering","strength"], text: "The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him." },
  // ── Zephaniah ──
  { ref: "Zephaniah 3:17", book: "Zephaniah", chapter: 3, topics: ["God","love","joy","salvation"], text: "The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing." },
  // ── Genesis ──
  { ref: "Genesis 1:1", book: "Genesis", chapter: 1, topics: ["creation","God"], text: "In the beginning God created the heaven and the earth." },
  { ref: "Genesis 1:27", book: "Genesis", chapter: 1, topics: ["creation","God","purpose"], text: "So God created man in his own image, in the image of God created he him; male and female created he them." },
  { ref: "Genesis 12:2", book: "Genesis", chapter: 12, topics: ["blessing","purpose","God","obedience"], text: "And I will make of thee a great nation, and I will bless thee, and make thy name great; and thou shalt be a blessing." },
  { ref: "Genesis 28:15", book: "Genesis", chapter: 28, topics: ["God","trust","promise","fear"], text: "And, behold, I am with thee, and will keep thee in all places whither thou goest, and will bring thee again into this land; for I will not leave thee, until I have done that which I have spoken to thee of." },
  { ref: "Genesis 50:20", book: "Genesis", chapter: 50, topics: ["suffering","purpose","God","hope"], text: "But as for you, ye thought evil against me; but God meant it unto good, to bring to pass, as it is this day, to save much people alive." },
  // ── Exodus ──
  { ref: "Exodus 14:14", book: "Exodus", chapter: 14, topics: ["enemies","God","peace","trust"], text: "The LORD shall fight for you, and ye shall hold your peace." },
  { ref: "Exodus 20:12", book: "Exodus", chapter: 20, topics: ["family","children","obedience"], text: "Honour thy father and thy mother: that thy days may be long upon the land which the LORD thy God giveth thee." },
  { ref: "Exodus 33:14", book: "Exodus", chapter: 33, topics: ["God","peace","rest","trust"], text: "And he said, My presence shall go with thee, and I will give thee rest." },
  // ── Numbers ──
  { ref: "Numbers 6:24", book: "Numbers", chapter: 6, topics: ["blessing","peace","grace","God"], text: "The LORD bless thee, and keep thee: The LORD make his face shine upon thee, and be gracious unto thee: The LORD lift up his countenance upon thee, and give thee peace." },
  // ── Deuteronomy ──
  { ref: "Deuteronomy 31:6", book: "Deuteronomy", chapter: 31, topics: ["fear","strength","God","trust"], text: "Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee." },
  { ref: "Deuteronomy 6:5", book: "Deuteronomy", chapter: 6, topics: ["love","obedience","God"], text: "And thou shalt love the LORD thy God with all thine heart, and with all thy soul, and with all thy might." },
  { ref: "Deuteronomy 28:2", book: "Deuteronomy", chapter: 28, topics: ["blessing","obedience","God"], text: "And all these blessings shall come on thee, and overtake thee, if thou shalt hearken unto the voice of the LORD thy God." },
  // ── Joshua ──
  { ref: "Joshua 1:9", book: "Joshua", chapter: 1, topics: ["fear","strength","God","trust"], text: "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest." },
  { ref: "Joshua 24:15", book: "Joshua", chapter: 24, topics: ["family","obedience","God","faith"], text: "As for me and my house, we will serve the LORD." },
  // ── Ruth ──
  { ref: "Ruth 1:16", book: "Ruth", chapter: 1, topics: ["love","family","loyalty","faith"], text: "And Ruth said, Intreat me not to leave thee, or to return from following after thee: for whither thou goest, I will go; and where thou lodgest, I will lodge: thy people shall be my people, and thy God my God." },
  // ── 1 Samuel ──
  { ref: "1 Samuel 16:7", book: "1 Samuel", chapter: 16, topics: ["God","purpose","humility","heart"], text: "But the LORD said unto Samuel, Look not on his countenance, or on the height of his stature; because I have refused him: for the LORD seeth not as man seeth; for man looketh on the outward appearance, but the LORD looketh on the heart." },
  // ── Esther ──
  { ref: "Esther 4:14", book: "Esther", chapter: 4, topics: ["purpose","God","courage"], text: "Who knoweth whether thou art come to the kingdom for such a time as this?" },
  // ── Job ──
  { ref: "Job 19:25", book: "Job", chapter: 19, topics: ["Jesus","hope","salvation","suffering"], text: "For I know that my redeemer liveth, and that he shall stand at the latter day upon the earth." },
  { ref: "Job 42:2", book: "Job", chapter: 42, topics: ["God","purpose","trust"], text: "I know that thou canst do every thing, and that no thought can be withholden from thee." },
  // ── Ecclesiastes ──
  { ref: "Ecclesiastes 3:1", book: "Ecclesiastes", chapter: 3, topics: ["purpose","God","wisdom"], text: "To every thing there is a season, and a time to every purpose under the heaven." },
  { ref: "Ecclesiastes 4:9", book: "Ecclesiastes", chapter: 4, topics: ["community","family","work","love"], text: "Two are better than one; because they have a good reward for their labour." },
  { ref: "Ecclesiastes 12:13", book: "Ecclesiastes", chapter: 12, topics: ["obedience","God","wisdom"], text: "Fear God, and keep his commandments: for this is the whole duty of man." },
  // ── 2 Chronicles ──
  { ref: "2 Chronicles 7:14", book: "2 Chronicles", chapter: 7, topics: ["prayer","forgiveness","healing","humility","God"], text: "If my people, which are called by my name, shall humble themselves, and pray, and seek my face, and turn from their wicked ways; then will I hear from heaven, and will forgive their sin, and will heal their land." },
  // ── Nehemiah ──
  { ref: "Nehemiah 8:10", book: "Nehemiah", chapter: 8, topics: ["joy","strength","God"], text: "The joy of the LORD is your strength." },
  // ── Song of Solomon ──
  { ref: "Song of Solomon 2:16", book: "Song of Solomon", chapter: 2, topics: ["love","marriage"], text: "My beloved is mine, and I am his: he feedeth among the lilies." },
  // ── Matthew ──
  { ref: "Matthew 6:33", book: "Matthew", chapter: 6, topics: ["God","trust","purpose","obedience"], text: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you." },
  { ref: "Matthew 11:28", book: "Matthew", chapter: 11, topics: ["Jesus","rest","peace","suffering"], text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest." },
  { ref: "Matthew 5:16", book: "Matthew", chapter: 5, topics: ["worship","obedience","God"], text: "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven." },
  { ref: "Matthew 5:9", book: "Matthew", chapter: 5, topics: ["peace","God","blessing"], text: "Blessed are the peacemakers: for they shall be called the children of God." },
  { ref: "Matthew 7:7", book: "Matthew", chapter: 7, topics: ["prayer","trust","God","faith"], text: "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you." },
  { ref: "Matthew 19:26", book: "Matthew", chapter: 19, topics: ["God","faith","hope","strength"], text: "With men this is impossible; but with God all things are possible." },
  { ref: "Matthew 22:37", book: "Matthew", chapter: 22, topics: ["love","obedience","God"], text: "Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind. This is the first and great commandment." },
  { ref: "Matthew 28:20", book: "Matthew", chapter: 28, topics: ["God","trust","obedience","Jesus"], text: "Teaching them to observe all things whatsoever I have commanded you: and, lo, I am with you alway, even unto the end of the world. Amen." },
  { ref: "Matthew 6:34", book: "Matthew", chapter: 6, topics: ["worry","trust","God"], text: "Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself." },
  { ref: "Matthew 5:3", book: "Matthew", chapter: 5, topics: ["humility","God","heaven","blessing"], text: "Blessed are the poor in spirit: for theirs is the kingdom of heaven." },
  { ref: "Matthew 5:4", book: "Matthew", chapter: 5, topics: ["suffering","hope","comfort","God"], text: "Blessed are they that mourn: for they shall be comforted." },
  { ref: "Matthew 5:44", book: "Matthew", chapter: 5, topics: ["enemies","love","prayer","obedience"], text: "But I say unto you, Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you." },
  { ref: "Matthew 6:9", book: "Matthew", chapter: 6, topics: ["prayer","God","worship"], text: "Our Father which art in heaven, Hallowed be thy name. Thy kingdom come. Thy will be done in earth, as it is in heaven." },
  { ref: "Matthew 6:14", book: "Matthew", chapter: 6, topics: ["forgiveness","God","sin","obedience"], text: "For if ye forgive men their trespasses, your heavenly Father will also forgive you." },
  { ref: "Matthew 7:12", book: "Matthew", chapter: 7, topics: ["love","obedience","community"], text: "Therefore all things whatsoever ye would that men should do to you, do ye even so to them: for this is the law and the prophets." },
  { ref: "Matthew 18:20", book: "Matthew", chapter: 18, topics: ["prayer","community","Jesus","worship"], text: "For where two or three are gathered together in my name, there am I in the midst of them." },
  { ref: "Matthew 28:19", book: "Matthew", chapter: 28, topics: ["obedience","Jesus","purpose","Holy Spirit"], text: "Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost." },
  // ── Mark ──
  { ref: "Mark 11:24", book: "Mark", chapter: 11, topics: ["prayer","faith","trust","God"], text: "Therefore I say unto you, What things soever ye desire, when ye pray, believe that ye receive them, and ye shall have them." },
  { ref: "Mark 16:15", book: "Mark", chapter: 16, topics: ["obedience","Jesus","purpose"], text: "And he said unto them, Go ye into all the world, and preach the gospel to every creature." },
  { ref: "Mark 9:23", book: "Mark", chapter: 9, topics: ["faith","hope","God","trust"], text: "Jesus said unto him, If thou canst believe, all things are possible to him that believeth." },
  { ref: "Mark 10:27", book: "Mark", chapter: 10, topics: ["God","faith","hope","strength"], text: "With men it is impossible, but not with God: for with God all things are possible." },
  { ref: "Mark 12:30", book: "Mark", chapter: 12, topics: ["love","obedience","God"], text: "And thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind, and with all thy strength: this is the first commandment." },
  // ── Luke ──
  { ref: "Luke 1:37", book: "Luke", chapter: 1, topics: ["God","faith","hope","strength"], text: "For with God nothing shall be impossible." },
  { ref: "Luke 1:45", book: "Luke", chapter: 1, topics: ["faith","blessing","hope"], text: "And blessed is she that believed: for there shall be a performance of those things which were told her from the Lord." },
  { ref: "Luke 6:31", book: "Luke", chapter: 6, topics: ["love","obedience","community"], text: "And as ye would that men should do to you, do ye also to them likewise." },
  { ref: "Luke 6:27", book: "Luke", chapter: 6, topics: ["love","enemies","obedience","prayer"], text: "But I say unto you which hear, Love your enemies, do good to them which hate you, Bless them that curse you, and pray for them which despitefully use you." },
  { ref: "Luke 11:9", book: "Luke", chapter: 11, topics: ["prayer","faith","trust","God"], text: "And I say unto you, Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you." },
  { ref: "Luke 6:38", book: "Luke", chapter: 6, topics: ["giving","money","blessing","obedience"], text: "Give, and it shall be given unto you; good measure, pressed down, and shaken together, and running over, shall men give into your bosom." },
  { ref: "Luke 12:22", book: "Luke", chapter: 12, topics: ["worry","trust","God","faith"], text: "And he said unto his disciples, Therefore I say unto you, Take no thought for your life, what ye shall eat; neither for the body, what ye shall put on." },
  { ref: "Luke 15:7", book: "Luke", chapter: 15, topics: ["salvation","joy","forgiveness","God"], text: "I say unto you, that likewise joy shall be in heaven over one sinner that repenteth, more than over ninety and nine just persons, which need no repentance." },
  // ── Acts ──
  { ref: "Acts 1:8", book: "Acts", chapter: 1, topics: ["Holy Spirit","purpose","obedience","Jesus"], text: "But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me both in Jerusalem, and in all Judaea, and in Samaria, and unto the uttermost part of the earth." },
  { ref: "Acts 4:12", book: "Acts", chapter: 4, topics: ["salvation","Jesus","faith"], text: "Neither is there salvation in any other: for there is none other name under heaven given among men, whereby we must be saved." },
  { ref: "Acts 2:38", book: "Acts", chapter: 2, topics: ["salvation","sin","Holy Spirit","forgiveness"], text: "Then Peter said unto them, Repent, and be baptized every one of you in the name of Jesus Christ for the remission of sins, and ye shall receive the gift of the Holy Ghost." },
  { ref: "Acts 16:31", book: "Acts", chapter: 16, topics: ["salvation","faith","family"], text: "And they said, Believe on the Lord Jesus Christ, and thou shalt be saved, and thy house." },
  // ── Romans ──
  { ref: "Romans 5:8", book: "Romans", chapter: 5, topics: ["love","salvation","sin","Jesus"], text: "But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us." },
  { ref: "Romans 6:23", book: "Romans", chapter: 6, topics: ["sin","salvation","death","Jesus"], text: "For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord." },
  { ref: "Romans 8:28", book: "Romans", chapter: 8, topics: ["purpose","God","trust","love"], text: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose." },
  { ref: "Romans 8:31", book: "Romans", chapter: 8, topics: ["God","trust","enemies","faith"], text: "What shall we then say to these things? If God be for us, who can be against us?" },
  { ref: "Romans 8:38", book: "Romans", chapter: 8, topics: ["love","death","God","faith"], text: "For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come, nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord." },
  { ref: "Romans 10:9", book: "Romans", chapter: 10, topics: ["salvation","faith","Jesus"], text: "That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved." },
  { ref: "Romans 12:2", book: "Romans", chapter: 12, topics: ["obedience","wisdom","renewal","God"], text: "And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God." },
  { ref: "Romans 15:13", book: "Romans", chapter: 15, topics: ["hope","joy","peace","Holy Spirit"], text: "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost." },
  { ref: "Romans 3:23", book: "Romans", chapter: 3, topics: ["sin","salvation","grace"], text: "For all have sinned, and come short of the glory of God." },
  { ref: "Romans 5:1", book: "Romans", chapter: 5, topics: ["peace","faith","salvation","Jesus"], text: "Therefore being justified by faith, we have peace with God through our Lord Jesus Christ." },
  { ref: "Romans 8:1", book: "Romans", chapter: 8, topics: ["salvation","sin","Jesus","forgiveness"], text: "There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but after the Spirit." },
  { ref: "Romans 12:12", book: "Romans", chapter: 12, topics: ["hope","prayer","suffering","patience"], text: "Rejoicing in hope; patient in tribulation; continuing instant in prayer." },
  { ref: "Romans 12:18", book: "Romans", chapter: 12, topics: ["peace","enemies","obedience","love"], text: "If it be possible, as much as lieth in you, live peaceably with all men." },
  // ── 1 Corinthians ──
  { ref: "1 Corinthians 3:16", book: "1 Corinthians", chapter: 3, topics: ["Holy Spirit","God","worship","temple"], text: "Know ye not that ye are the temple of God, and that the Spirit of God dwelleth in you?" },
  { ref: "1 Corinthians 10:13", book: "1 Corinthians", chapter: 10, topics: ["temptation","God","faith","strength"], text: "There hath no temptation taken you but such as is common to man: but God is faithful, who will not suffer you to be tempted above that ye are able; but will with the temptation also make a way to escape, that ye may be able to bear it." },
  { ref: "1 Corinthians 13:4", book: "1 Corinthians", chapter: 13, topics: ["love","marriage","family","community"], text: "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up." },
  { ref: "1 Corinthians 13:13", book: "1 Corinthians", chapter: 13, topics: ["love","faith","hope"], text: "And now abideth faith, hope, charity, these three; but the greatest of these is charity." },
  { ref: "1 Corinthians 15:58", book: "1 Corinthians", chapter: 15, topics: ["work","obedience","hope","purpose"], text: "Therefore, my beloved brethren, be ye stedfast, unmoveable, always abounding in the work of the Lord, forasmuch as ye know that your labour is not in vain in the Lord." },
  { ref: "1 Corinthians 2:9", book: "1 Corinthians", chapter: 2, topics: ["heaven","hope","God","joy"], text: "But as it is written, Eye hath not seen, nor ear heard, neither have entered into the heart of man, the things which God hath prepared for them that love him." },
  { ref: "1 Corinthians 6:19", book: "1 Corinthians", chapter: 6, topics: ["Holy Spirit","God","worship","temple"], text: "What? know ye not that your body is the temple of the Holy Ghost which is in you, which ye have of God, and ye are not your own?" },
  { ref: "1 Corinthians 13:7", book: "1 Corinthians", chapter: 13, topics: ["love","hope","faith","family"], text: "Beareth all things, believeth all things, hopeth all things, endureth all things." },
  { ref: "1 Corinthians 15:55", book: "1 Corinthians", chapter: 15, topics: ["death","salvation","hope","Jesus"], text: "O death, where is thy sting? O grave, where is thy victory?" },
  // ── 2 Corinthians ──
  { ref: "2 Corinthians 4:17", book: "2 Corinthians", chapter: 4, topics: ["suffering","hope","heaven","glory"], text: "For our light affliction, which is but for a moment, worketh for us a far more exceeding and eternal weight of glory." },
  { ref: "2 Corinthians 5:17", book: "2 Corinthians", chapter: 5, topics: ["salvation","renewal","Jesus","Holy Spirit"], text: "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new." },
  { ref: "2 Corinthians 9:8", book: "2 Corinthians", chapter: 9, topics: ["grace","God","blessing","work"], text: "And God is able to make all grace abound toward you; that ye, always having all sufficiency in all things, may abound to every good work." },
  { ref: "2 Corinthians 12:9", book: "2 Corinthians", chapter: 12, topics: ["grace","strength","suffering","God"], text: "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness." },
  { ref: "2 Corinthians 4:16", book: "2 Corinthians", chapter: 4, topics: ["renewal","hope","suffering","strength"], text: "For which cause we faint not; but though our outward man perish, yet the inward man is renewed day by day." },
  { ref: "2 Corinthians 5:7", book: "2 Corinthians", chapter: 5, topics: ["faith","trust","obedience"], text: "For we walk by faith, not by sight." },
  // ── Galatians ──
  { ref: "Galatians 2:20", book: "Galatians", chapter: 2, topics: ["faith","Jesus","salvation","love"], text: "I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me: and the life which I now live in the flesh I live by the faith of the Son of God, who loved me, and gave himself for me." },
  { ref: "Galatians 5:22", book: "Galatians", chapter: 5, topics: ["Holy Spirit","love","joy","peace","faith"], text: "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, Meekness, temperance: against such there is no law." },
  { ref: "Galatians 6:9", book: "Galatians", chapter: 6, topics: ["work","hope","suffering","obedience"], text: "And let us not be weary in well doing: for in due season we shall reap, if we faint not." },
  // ── Ephesians ──
  { ref: "Ephesians 2:8", book: "Ephesians", chapter: 2, topics: ["grace","salvation","faith"], text: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God: Not of works, lest any man should boast." },
  { ref: "Ephesians 3:20", book: "Ephesians", chapter: 3, topics: ["God","prayer","faith","hope"], text: "Now unto him that is able to do exceeding abundantly above all that we ask or think, according to the power that worketh in us." },
  { ref: "Ephesians 4:32", book: "Ephesians", chapter: 4, topics: ["forgiveness","love","community","family"], text: "And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you." },
  { ref: "Ephesians 6:10", book: "Ephesians", chapter: 6, topics: ["strength","temptation","God","enemies"], text: "Finally, my brethren, be strong in the Lord, and in the power of his might. Put on the whole armour of God, that ye may be able to stand against the wiles of the devil." },
  { ref: "Ephesians 5:25", book: "Ephesians", chapter: 5, topics: ["marriage","love","husband","wife"], text: "Husbands, love your wives, even as Christ also loved the church, and gave himself for it." },
  { ref: "Ephesians 6:1", book: "Ephesians", chapter: 6, topics: ["children","family","obedience"], text: "Children, obey your parents in the Lord: for this is right." },
  { ref: "Ephesians 6:4", book: "Ephesians", chapter: 6, topics: ["children","family","obedience","parents"], text: "And, ye fathers, provoke not your children to wrath: but bring them up in the nurture and admonition of the Lord." },
  // ── Philippians ──
  { ref: "Philippians 1:6", book: "Philippians", chapter: 1, topics: ["purpose","hope","God","trust"], text: "Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ." },
  { ref: "Philippians 4:6", book: "Philippians", chapter: 4, topics: ["prayer","worry","trust","God"], text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God." },
  { ref: "Philippians 4:7", book: "Philippians", chapter: 4, topics: ["peace","prayer","God","worry"], text: "And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus." },
  { ref: "Philippians 4:13", book: "Philippians", chapter: 4, topics: ["strength","Jesus","faith","work"], text: "I can do all things through Christ which strengtheneth me." },
  { ref: "Philippians 4:19", book: "Philippians", chapter: 4, topics: ["God","trust","money","blessing"], text: "But my God shall supply all your need according to his riches in glory by Christ Jesus." },
  { ref: "Philippians 2:13", book: "Philippians", chapter: 2, topics: ["purpose","God","obedience","Holy Spirit"], text: "For it is God which worketh in you both to will and to do of his good pleasure." },
  { ref: "Philippians 4:4", book: "Philippians", chapter: 4, topics: ["joy","worship","God"], text: "Rejoice in the Lord alway: and again I say, Rejoice." },
  { ref: "Philippians 4:8", book: "Philippians", chapter: 4, topics: ["wisdom","mind","obedience","peace"], text: "Finally, brethren, whatsoever things are true, whatsoever things are honest, whatsoever things are just, whatsoever things are pure, whatsoever things are lovely, whatsoever things are of good report; if there be any virtue, and if there be any praise, think on these things." },
  // ── Colossians ──
  { ref: "Colossians 3:16", book: "Colossians", chapter: 3, topics: ["worship","wisdom","community","Holy Spirit"], text: "Let the word of Christ dwell in you richly in all wisdom; teaching and admonishing one another in psalms and hymns and spiritual songs, singing with grace in your hearts to the Lord." },
  { ref: "Colossians 3:23", book: "Colossians", chapter: 3, topics: ["work","obedience","God"], text: "And whatsoever ye do, do it heartily, as to the Lord, and not unto men." },
  { ref: "Colossians 3:14", book: "Colossians", chapter: 3, topics: ["love","community","family"], text: "And above all these things put on charity, which is the bond of perfectness." },
  { ref: "Colossians 4:2", book: "Colossians", chapter: 4, topics: ["prayer","worship","God","thanksgiving"], text: "Continue in prayer, and watch in the same with thanksgiving." },
  // ── 1 Thessalonians ──
  { ref: "1 Thessalonians 5:16", book: "1 Thessalonians", chapter: 5, topics: ["joy","prayer","worship","God"], text: "Rejoice evermore. Pray without ceasing. In every thing give thanks: for this is the will of God in Christ Jesus concerning you." },
  { ref: "1 Thessalonians 4:13", book: "1 Thessalonians", chapter: 4, topics: ["death","hope","heaven","Jesus"], text: "But I would not have you to be ignorant, brethren, concerning them which are asleep, that ye sorrow not, even as others which have no hope." },
  { ref: "1 Thessalonians 5:11", book: "1 Thessalonians", chapter: 5, topics: ["community","love","family","encouragement"], text: "Wherefore comfort yourselves together, and edify one another, even as also ye do." },
  // ── 2 Thessalonians ──
  { ref: "2 Thessalonians 3:3", book: "2 Thessalonians", chapter: 3, topics: ["God","trust","enemies","temptation"], text: "But the Lord is faithful, who shall stablish you, and keep you from evil." },
  // ── 1 Timothy ──
  { ref: "1 Timothy 4:12", book: "1 Timothy", chapter: 4, topics: ["love","faith","obedience","youth"], text: "Let no man despise thy youth; but be thou an example of the believers, in word, in conversation, in charity, in spirit, in faith, in purity." },
  { ref: "1 Timothy 6:6", book: "1 Timothy", chapter: 6, topics: ["money","wisdom","obedience"], text: "But godliness with contentment is great gain." },
  { ref: "1 Timothy 6:10", book: "1 Timothy", chapter: 6, topics: ["money","sin","obedience"], text: "For the love of money is the root of all evil: which while some coveted after, they have erred from the faith, and pierced themselves through with many sorrows." },
  // ── 2 Timothy ──
  { ref: "2 Timothy 1:7", book: "2 Timothy", chapter: 1, topics: ["fear","Holy Spirit","love","strength"], text: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind." },
  { ref: "2 Timothy 3:16", book: "2 Timothy", chapter: 3, topics: ["wisdom","obedience","God"], text: "All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness." },
  { ref: "2 Timothy 4:7", book: "2 Timothy", chapter: 4, topics: ["faith","work","hope","suffering"], text: "I have fought a good fight, I have finished my course, I have kept the faith." },
  // ── Hebrews ──
  { ref: "Hebrews 4:12", book: "Hebrews", chapter: 4, topics: ["wisdom","God","obedience"], text: "For the word of God is quick, and powerful, and sharper than any twoedged sword, piercing even to the dividing asunder of soul and spirit, and of the joints and marrow, and is a discerner of the thoughts and intents of the heart." },
  { ref: "Hebrews 11:1", book: "Hebrews", chapter: 11, topics: ["faith","hope","trust"], text: "Now faith is the substance of things hoped for, the evidence of things not seen." },
  { ref: "Hebrews 11:6", book: "Hebrews", chapter: 11, topics: ["faith","God","prayer","trust"], text: "But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him." },
  { ref: "Hebrews 12:1", book: "Hebrews", chapter: 12, topics: ["faith","Jesus","suffering","obedience"], text: "Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us, Looking unto Jesus the author and finisher of our faith." },
  { ref: "Hebrews 13:8", book: "Hebrews", chapter: 13, topics: ["Jesus","God","faith","trust"], text: "Jesus Christ the same yesterday, and to day, and for ever." },
  { ref: "Hebrews 4:16", book: "Hebrews", chapter: 4, topics: ["grace","prayer","mercy","God"], text: "Let us therefore come boldly unto the throne of grace, that we may obtain mercy, and find grace to help in time of need." },
  { ref: "Hebrews 6:19", book: "Hebrews", chapter: 6, topics: ["hope","faith","salvation","anchor"], text: "Which hope we have as an anchor of the soul, both sure and stedfast, and which entereth into that within the veil." },
  { ref: "Hebrews 10:25", book: "Hebrews", chapter: 10, topics: ["community","worship","obedience"], text: "Not forsaking the assembling of ourselves together, as the manner of some is; but exhorting one another: and so much the more, as ye see the day approaching." },
  { ref: "Hebrews 12:2", book: "Hebrews", chapter: 12, topics: ["faith","Jesus","joy","suffering"], text: "Looking unto Jesus the author and finisher of our faith; who for the joy that was set before him endured the cross, despising the shame, and is set down at the right hand of the throne of God." },
  // ── James ──
  { ref: "James 1:2", book: "James", chapter: 1, topics: ["suffering","joy","faith","temptation"], text: "My brethren, count it all joy when ye fall into divers temptations; Knowing this, that the trying of your faith worketh patience." },
  { ref: "James 1:17", book: "James", chapter: 1, topics: ["God","grace","blessing","gifts"], text: "Every good gift and every perfect gift is from above, and cometh down from the Father of lights, with whom is no variableness, neither shadow of turning." },
  { ref: "James 2:17", book: "James", chapter: 2, topics: ["faith","work","obedience"], text: "Even so faith, if it hath not works, is dead, being alone." },
  { ref: "James 4:7", book: "James", chapter: 4, topics: ["temptation","sin","God","obedience"], text: "Submit yourselves therefore to God. Resist the devil, and he will flee from you." },
  { ref: "James 5:16", book: "James", chapter: 5, topics: ["prayer","healing","forgiveness","community"], text: "The effectual fervent prayer of a righteous man availeth much." },
  { ref: "James 1:5", book: "James", chapter: 1, topics: ["wisdom","prayer","God","faith"], text: "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him." },
  { ref: "James 4:8", book: "James", chapter: 4, topics: ["God","obedience","sin","trust"], text: "Draw nigh to God, and he will draw nigh to you. Cleanse your hands, ye sinners; and purify your hearts, ye double minded." },
  // ── 1 Peter ──
  { ref: "1 Peter 4:8", book: "1 Peter", chapter: 4, topics: ["love","forgiveness","community","family"], text: "And above all things have fervent charity among yourselves: for charity shall cover the multitude of sins." },
  { ref: "1 Peter 5:7", book: "1 Peter", chapter: 5, topics: ["worry","trust","God","peace"], text: "Casting all your care upon him; for he careth for you." },
  { ref: "1 Peter 3:9", book: "1 Peter", chapter: 3, topics: ["love","enemies","blessing","obedience"], text: "Not rendering evil for evil, or railing for railing: but contrariwise blessing; knowing that ye are thereunto called, that ye should inherit a blessing." },
  { ref: "1 Peter 5:8", book: "1 Peter", chapter: 5, topics: ["temptation","sin","enemies","wisdom"], text: "Be sober, be vigilant; because your adversary the devil, as a roaring lion, walketh about, seeking whom he may devour." },
  // ── 2 Peter ──
  { ref: "2 Peter 1:4", book: "2 Peter", chapter: 1, topics: ["grace","God","holy spirit","promise"], text: "Whereby are given unto us exceeding great and precious promises: that by these ye might be partakers of the divine nature." },
  { ref: "2 Peter 3:9", book: "2 Peter", chapter: 3, topics: ["salvation","sin","God","grace"], text: "The Lord is not slack concerning his promise, as some men count slackness; but is longsuffering to us-ward, not willing that any should perish, but that all should come to repentance." },
  // ── 1 John ──
  { ref: "1 John 1:9", book: "1 John", chapter: 1, topics: ["forgiveness","sin","grace","God"], text: "If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness." },
  { ref: "1 John 4:4", book: "1 John", chapter: 4, topics: ["God","Holy Spirit","strength","trust"], text: "Ye are of God, little children, and have overcome them: because greater is he that is in you, than he that is in the world." },
  { ref: "1 John 4:8", book: "1 John", chapter: 4, topics: ["love","God"], text: "He that loveth not knoweth not God; for God is love." },
  { ref: "1 John 4:19", book: "1 John", chapter: 4, topics: ["love","God"], text: "We love him, because he first loved us." },
  { ref: "1 John 4:18", book: "1 John", chapter: 4, topics: ["fear","love","peace","God"], text: "There is no fear in love; but perfect love casteth out fear: because fear hath torment. He that feareth is not made perfect in love." },
  { ref: "1 John 3:16", book: "1 John", chapter: 3, topics: ["love","Jesus","sacrifice","obedience"], text: "Hereby perceive we the love of God, because he laid down his life for us: and we ought to lay down our lives for the brethren." },
  { ref: "1 John 5:4", book: "1 John", chapter: 5, topics: ["faith","victory","God","strength"], text: "For whatsoever is born of God overcometh the world: and this is the victory that overcometh the world, even our faith." },
  // ── 3 John ──
  { ref: "3 John 1:2", book: "3 John", chapter: 1, topics: ["healing","blessing","prosperity","God"], text: "Beloved, I wish above all things that thou mayest prosper and be in health, even as thy soul prospereth." },
  // ── Jude ──
  { ref: "Jude 1:24", book: "Jude", chapter: 1, topics: ["God","joy","salvation","trust"], text: "Now unto him that is able to keep you from falling, and to present you faultless before the presence of his glory with exceeding joy." },
  // ── Revelation ──
  { ref: "Revelation 3:20", book: "Revelation", chapter: 3, topics: ["Jesus","salvation","obedience","trust"], text: "Behold, I stand at the door, and knock: if any man hear my voice, and open the door, I will come in to him, and will sup with him, and he with me." },
  { ref: "Revelation 21:4", book: "Revelation", chapter: 21, topics: ["death","heaven","hope","God"], text: "And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain: for the former things are passed away." },
  { ref: "Revelation 22:20", book: "Revelation", chapter: 22, topics: ["Jesus","hope","heaven"], text: "He which testifieth these things saith, Surely I come quickly. Amen. Even so, come, Lord Jesus." },
  { ref: "Revelation 21:3", book: "Revelation", chapter: 21, topics: ["God","heaven","worship","community"], text: "And I heard a great voice out of heaven saying, Behold, the tabernacle of God is with men, and he will dwell with them, and they shall be his people, and God himself shall be with them, and be their God." },
];
