// Ported from faithspark-web/src/constants/gamedata.ts — TRIVIA_ALL and
// FILLINS_ALL question banks used by the Bible Trivia and Fill in the Blank games.

export const TRIVIA_ALL = [
  // --- EASY (~70) ---
  { q: "How many books are in the Bible?", a: 1, opts: ["64", "66", "68", "72"] },
  { q: "Who was swallowed by a great fish?", a: 0, opts: ["Jonah", "Elijah", "Paul", "Peter"] },
  { q: "What was the name of Abraham's wife?", a: 2, opts: ["Rachel", "Rebekah", "Sarah", "Miriam"] },
  { q: "Which disciple betrayed Jesus?", a: 3, opts: ["Peter", "Thomas", "Matthew", "Judas"] },
  { q: "In what city was Jesus born?", a: 1, opts: ["Nazareth", "Bethlehem", "Jerusalem", "Jericho"] },
  { q: "How many days did God take to create the world?", a: 0, opts: ["6", "7", "8", "10"] },
  { q: "Who built the ark?", a: 2, opts: ["Moses", "Abraham", "Noah", "Lot"] },
  { q: "How many commandments did God give Moses?", a: 3, opts: ["5", "7", "8", "10"] },
  { q: "What is the first book of the Bible?", a: 0, opts: ["Genesis", "Exodus", "Psalms", "Matthew"] },
  { q: "Who was the first man created by God?", a: 1, opts: ["Noah", "Adam", "Cain", "Abel"] },
  { q: "What is the last book of the Bible?", a: 2, opts: ["Jude", "3 John", "Revelation", "Hebrews"] },
  { q: "Who was thrown into the lions' den?", a: 3, opts: ["Shadrach", "Elijah", "Ezekiel", "Daniel"] },
  { q: "How many apostles did Jesus choose?", a: 0, opts: ["12", "7", "10", "14"] },
  { q: "What river was Jesus baptized in?", a: 1, opts: ["Nile", "Jordan", "Euphrates", "Tigris"] },
  { q: "Who was the mother of Jesus?", a: 2, opts: ["Martha", "Elizabeth", "Mary", "Salome"] },
  { q: "What did God create on the first day?", a: 3, opts: ["Animals", "Plants", "Sun and Moon", "Light"] },
  { q: "Who killed Goliath?", a: 0, opts: ["David", "Saul", "Jonathan", "Samuel"] },
  { q: "How many books are in the New Testament?", a: 1, opts: ["26", "27", "28", "29"] },
  { q: "What was the first miracle Jesus performed?", a: 2, opts: ["Healing a blind man", "Walking on water", "Turning water into wine", "Feeding 5000"] },
  { q: "What fruit did Eve eat in the Garden of Eden?", a: 3, opts: ["A pear", "A pomegranate", "A fig", "Forbidden fruit from the tree of knowledge"] },
  { q: "Who parted the Red Sea?", a: 0, opts: ["Moses", "Aaron", "Joshua", "Elijah"] },
  { q: "What is the shortest verse in the Bible?", a: 1, opts: ["'God is love'", "'Jesus wept'", "'Pray without ceasing'", "'Amen'"] },
  { q: "Who was sold by his brothers into slavery?", a: 2, opts: ["Benjamin", "Reuben", "Joseph", "Simeon"] },
  { q: "On what day did Jesus rise from the dead?", a: 3, opts: ["The first day", "The second day", "After six days", "The third day"] },
  { q: "Who wrote most of the Psalms?", a: 0, opts: ["David", "Solomon", "Moses", "Asaph"] },
  { q: "What is the Golden Rule?", a: 1, opts: ["Love God above all", "Do unto others as you would have them do unto you", "Honor your father and mother", "Fear the Lord"] },
  { q: "Who was the first king of Israel?", a: 2, opts: ["David", "Solomon", "Saul", "Samuel"] },
  { q: "Who wrote the book of Revelation?", a: 3, opts: ["Peter", "Paul", "James", "John"] },
  { q: "What bird did Noah first send out from the ark?", a: 0, opts: ["A raven", "A dove", "A sparrow", "An eagle"] },
  { q: "In which garden was Jesus betrayed?", a: 1, opts: ["Eden", "Gethsemane", "Galilee", "Nazareth"] },
  { q: "How many people did Jesus feed with five loaves and two fish?", a: 2, opts: ["3000", "4000", "5000", "7000"] },
  { q: "Who was the tax collector who climbed a tree to see Jesus?", a: 3, opts: ["Matthew", "Simon", "Bartholomew", "Zacchaeus"] },
  { q: "What language was most of the Old Testament written in?", a: 0, opts: ["Hebrew", "Greek", "Aramaic", "Latin"] },
  { q: "Who was Abraham's son of promise?", a: 1, opts: ["Ishmael", "Isaac", "Jacob", "Esau"] },
  { q: "How many days and nights did it rain during Noah's flood?", a: 2, opts: ["20", "30", "40", "50"] },
  { q: "Which angel appeared to Mary to announce she would bear Jesus?", a: 3, opts: ["Michael", "Raphael", "Uriel", "Gabriel"] },
  { q: "Who was the father of John the Baptist?", a: 0, opts: ["Zacharias", "Joseph", "Simeon", "Eli"] },
  { q: "What did the wise men follow to find Jesus?", a: 1, opts: ["An angel", "A star", "A pillar of fire", "A cloud"] },
  { q: "Who wrote the majority of the New Testament letters?", a: 2, opts: ["Peter", "John", "Paul", "James"] },
  { q: "What was Saul's name changed to?", a: 3, opts: ["Simon", "Silas", "Stephen", "Paul"] },
  { q: "How long was Jesus in the wilderness being tempted?", a: 0, opts: ["40 days", "30 days", "7 days", "20 days"] },
  { q: "Who was the brother of Mary and Martha?", a: 1, opts: ["Simon", "Lazarus", "Andrew", "Philip"] },
  { q: "What is the longest book in the Bible?", a: 2, opts: ["Genesis", "Isaiah", "Psalms", "Jeremiah"] },
  { q: "How many plagues did God send on Egypt?", a: 3, opts: ["7", "8", "9", "10"] },
  { q: "Who was the wisest king of Israel?", a: 0, opts: ["Solomon", "David", "Asa", "Hezekiah"] },
  { q: "On which mountain did Moses receive the Ten Commandments?", a: 1, opts: ["Mount Carmel", "Mount Sinai", "Mount Zion", "Mount Nebo"] },
  { q: "Who denied Jesus three times?", a: 2, opts: ["John", "Thomas", "Peter", "Andrew"] },
  { q: "What sea did Jesus walk on?", a: 3, opts: ["Red Sea", "Dead Sea", "Mediterranean Sea", "Sea of Galilee"] },
  { q: "Who was the mother of Moses?", a: 0, opts: ["Jochebed", "Miriam", "Zipporah", "Pharaoh's daughter"] },
  { q: "What is the first commandment?", a: 1, opts: ["Honor your father and mother", "You shall have no other gods before me", "Do not murder", "Do not steal"] },
  { q: "Who was the father of the Jewish nation?", a: 2, opts: ["Isaac", "Jacob", "Abraham", "Noah"] },
  { q: "What did Jesus say before he died on the cross: 'It is ...'", a: 3, opts: ["Beginning", "Done", "Written", "Finished"] },
  { q: "What was Adam made from?", a: 0, opts: ["Dust of the ground", "Water", "Clay and fire", "Stone"] },
  { q: "What did Eve give to Adam in the garden?", a: 1, opts: ["A flower", "The forbidden fruit", "Water", "A garment"] },
  { q: "Who was known as the 'man after God's own heart'?", a: 2, opts: ["Abraham", "Moses", "David", "Elijah"] },
  { q: "How many days was Lazarus in the tomb before Jesus raised him?", a: 3, opts: ["1", "2", "3", "4"] },
  { q: "What is the first book of the New Testament?", a: 0, opts: ["Matthew", "Mark", "Luke", "John"] },
  { q: "Who was stoned to death for his faith in Acts?", a: 1, opts: ["Philip", "Stephen", "Barnabas", "Silas"] },
  { q: "In what city was Saul converted on the road to?", a: 2, opts: ["Jerusalem", "Antioch", "Damascus", "Rome"] },
  { q: "What was the sign of God's covenant with Noah?", a: 3, opts: ["A star", "A dove", "A cloud", "A rainbow"] },
  { q: "Who was Joshua's predecessor as leader of Israel?", a: 0, opts: ["Moses", "Aaron", "Caleb", "Samuel"] },
  { q: "Who was the first murderer in the Bible?", a: 1, opts: ["Lamech", "Cain", "Esau", "Pharaoh"] },
  { q: "What book comes after Genesis?", a: 2, opts: ["Leviticus", "Numbers", "Exodus", "Deuteronomy"] },
  { q: "What is the second greatest commandment according to Jesus?", a: 3, opts: ["Honor your parents", "Do not kill", "Keep the Sabbath", "Love your neighbor as yourself"] },
  { q: "How many books are in the Old Testament?", a: 0, opts: ["39", "37", "40", "36"] },
  { q: "Who was Jesus's earthly father?", a: 1, opts: ["Zacharias", "Joseph", "Simon", "Eli"] },
  { q: "Who led the Israelites into the Promised Land after Moses?", a: 2, opts: ["Aaron", "Caleb", "Joshua", "Samuel"] },
  { q: "What is the shortest book in the Old Testament?", a: 3, opts: ["Haggai", "Nahum", "Micah", "Obadiah"] },
  { q: "What was Jesus's hometown?", a: 0, opts: ["Nazareth", "Bethlehem", "Jerusalem", "Capernaum"] },
  { q: "Who baptized Jesus?", a: 1, opts: ["Peter", "John the Baptist", "Andrew", "Philip"] },

  // --- MEDIUM (~80) ---
  { q: "Who was the mother of Samuel?", a: 2, opts: ["Deborah", "Ruth", "Hannah", "Naomi"] },
  { q: "What material was the ark of the covenant made of?", a: 3, opts: ["Cedar wood", "Olive wood", "Stone", "Acacia wood"] },
  { q: "Who was Boaz's wife in the book of Ruth?", a: 0, opts: ["Ruth", "Naomi", "Orpah", "Abigail"] },
  { q: "What is the name of the hill where Jesus was crucified?", a: 1, opts: ["Mount of Olives", "Golgotha", "Sinai", "Zion"] },
  { q: "Which prophet was taken to heaven in a whirlwind?", a: 2, opts: ["Elisha", "Isaiah", "Elijah", "Ezekiel"] },
  { q: "Who was the father of Solomon?", a: 3, opts: ["Saul", "Samuel", "Jonathan", "David"] },
  { q: "What is the name of the angel who appeared to Gideon?", a: 0, opts: ["The angel of the LORD", "Gabriel", "Michael", "Raphael"] },
  { q: "How many years did the Israelites wander in the wilderness?", a: 1, opts: ["20", "40", "30", "50"] },
  { q: "Who was Esau's twin brother?", a: 2, opts: ["Ishmael", "Reuben", "Jacob", "Levi"] },
  { q: "What is the name of the sea the Israelites crossed?", a: 3, opts: ["Dead Sea", "Sea of Galilee", "Mediterranean Sea", "Red Sea"] },
  { q: "Who wrote the book of Acts?", a: 0, opts: ["Luke", "Paul", "Peter", "John"] },
  { q: "Who was Barnabas's cousin who accompanied Paul?", a: 1, opts: ["Silas", "Mark", "Titus", "Timothy"] },
  { q: "What occupation was Peter before following Jesus?", a: 2, opts: ["Tax collector", "Carpenter", "Fisherman", "Tent maker"] },
  { q: "In which book do we find the Beatitudes?", a: 3, opts: ["Luke 6", "Mark 5", "John 4", "Matthew 5"] },
  { q: "How many years did Israel serve in Egypt?", a: 0, opts: ["430", "400", "350", "500"] },
  { q: "Who replaced Judas as the twelfth apostle?", a: 1, opts: ["Silas", "Matthias", "Barnabas", "Stephen"] },
  { q: "What is the name of the well where Jesus met the Samaritan woman?", a: 2, opts: ["En Gedi", "Marah", "Jacob's Well", "Beersheba"] },
  { q: "Which king saw the writing on the wall?", a: 3, opts: ["Nebuchadnezzar", "Cyrus", "Darius", "Belshazzar"] },
  { q: "What did Samson's strength lie in?", a: 0, opts: ["His hair", "His shield", "His sword", "His belt"] },
  { q: "Who was the prophetess who judged Israel before Barak?", a: 1, opts: ["Miriam", "Deborah", "Huldah", "Abigail"] },
  { q: "How many years did Methuselah live?", a: 2, opts: ["777", "900", "969", "999"] },
  { q: "What was the occupation of Matthew before he followed Jesus?", a: 3, opts: ["Fisherman", "Shepherd", "Carpenter", "Tax collector"] },
  { q: "Which book of the Bible has the most chapters?", a: 0, opts: ["Psalms", "Genesis", "Isaiah", "Jeremiah"] },
  { q: "How many loaves of bread did Jesus use to feed 4,000?", a: 1, opts: ["5", "7", "10", "12"] },
  { q: "Who was thrown into a fiery furnace in Babylon?", a: 2, opts: ["Daniel and two others", "Daniel, Ezekiel and Isaiah", "Shadrach, Meshach and Abednego", "Ezekiel and two others"] },
  { q: "What is the name of the stream where David picked up five stones?", a: 3, opts: ["Kidron", "Jordan", "Jabbok", "Brook Elah"] },
  { q: "Who anointed David as king?", a: 0, opts: ["Samuel", "Elijah", "Nathan", "Zadok"] },
  { q: "In what language was most of the New Testament written?", a: 1, opts: ["Latin", "Greek", "Aramaic", "Hebrew"] },
  { q: "What is the name of the mount from which Jesus ascended to heaven?", a: 2, opts: ["Mount Zion", "Mount Sinai", "Mount of Olives", "Mount Carmel"] },
  { q: "Which king of Israel had 700 wives?", a: 3, opts: ["David", "Saul", "Ahab", "Solomon"] },
  { q: "Who was the father of James and John the disciples?", a: 0, opts: ["Zebedee", "Alphaeus", "Jonas", "Salome"] },
  { q: "What gift did the Holy Spirit give at Pentecost?", a: 1, opts: ["Healing", "Speaking in tongues", "Prophecy", "Wisdom"] },
  { q: "Who was the Roman governor who sentenced Jesus to death?", a: 2, opts: ["Herod", "Caesar", "Pontius Pilate", "Claudius"] },
  { q: "Who wrote the book of Hebrews?", a: 3, opts: ["Peter", "John", "Luke", "Authorship debated, possibly Paul"] },
  { q: "Which prophet married a prostitute as a sign of God's love for Israel?", a: 0, opts: ["Hosea", "Amos", "Micah", "Joel"] },
  { q: "What was the sign given to the shepherds about the baby Jesus?", a: 1, opts: ["A star in the east", "A baby wrapped in swaddling clothes in a manger", "An angel standing in the field", "A bright light from heaven"] },
  { q: "Who was the first Gentile convert baptized by Peter?", a: 2, opts: ["Lydia", "The Ethiopian eunuch", "Cornelius", "The Philippian jailer"] },
  { q: "How many days was Jesus on earth after his resurrection?", a: 3, opts: ["7", "20", "30", "40"] },
  { q: "What miracle happened when Paul and Silas were in prison?", a: 0, opts: ["An earthquake opened the prison doors", "An angel appeared", "The guards fell asleep", "A fire broke out"] },
  { q: "How many sons did Jacob have?", a: 1, opts: ["10", "12", "11", "13"] },
  { q: "Who was the Gentile woman who showed great faith and whose daughter Jesus healed?", a: 2, opts: ["A Samaritan woman", "A Roman centurion's daughter", "A Syro-Phoenician woman", "A Greek woman"] },
  { q: "Which disciple walked on water with Jesus?", a: 3, opts: ["John", "Andrew", "James", "Peter"] },
  { q: "Who was the first judge of Israel mentioned in the book of Judges?", a: 0, opts: ["Othniel", "Ehud", "Shamgar", "Deborah"] },
  { q: "What did Jacob's name mean?", a: 1, opts: ["Beloved", "Supplanter", "Blessed", "Faithful"] },
  { q: "Where did Elijah go after fleeing from Jezebel?", a: 2, opts: ["Jordan River", "Jerusalem", "Mount Horeb", "Mount Carmel"] },
  { q: "Who was Moses's father-in-law?", a: 3, opts: ["Aaron", "Caleb", "Amram", "Jethro"] },
  { q: "Which book contains the story of the Tower of Babel?", a: 0, opts: ["Genesis", "Exodus", "Numbers", "Deuteronomy"] },
  { q: "How many silver coins was Joseph sold for?", a: 1, opts: ["10", "20", "30", "40"] },
  { q: "Who was king of Judah when the temple was repaired and the Book of the Law was found?", a: 2, opts: ["Hezekiah", "Asa", "Josiah", "Jehoshaphat"] },
  { q: "What is the name of Abraham's servant who found a wife for Isaac?", a: 3, opts: ["Lot", "Aner", "Eliezer", "Mamre"] },
  { q: "Which apostle is called 'the beloved disciple' in the Gospel of John?", a: 0, opts: ["John", "Peter", "Andrew", "James"] },
  { q: "Who was the queen who visited Solomon because of his wisdom?", a: 1, opts: ["Jezebel", "The Queen of Sheba", "Esther", "Bathsheba"] },
  { q: "How many chapters are in the book of Psalms?", a: 2, opts: ["100", "120", "150", "180"] },
  { q: "What did God change Jacob's name to?", a: 3, opts: ["Israel", "Abraham", "Joseph", "Israel"] },
  { q: "Who was the high priest during Jesus's trial?", a: 0, opts: ["Caiaphas", "Annas", "Eli", "Uzziah"] },
  { q: "What did the prodigal son demand from his father?", a: 1, opts: ["His blessing", "His inheritance early", "Permission to travel", "Forgiveness"] },
  { q: "Which book of the Bible is a love poem?", a: 2, opts: ["Proverbs", "Ecclesiastes", "Song of Solomon", "Lamentations"] },
  { q: "Where was Saul of Tarsus going when he was converted?", a: 3, opts: ["Jerusalem", "Jericho", "Antioch", "Damascus"] },
  { q: "What was the name of the giant Philistine David killed?", a: 0, opts: ["Goliath", "Saph", "Ishbi-benob", "Lahmi"] },
  { q: "Who wrote Lamentations?", a: 1, opts: ["Isaiah", "Jeremiah", "Ezekiel", "Daniel"] },
  { q: "How many chapters does the book of John have?", a: 2, opts: ["19", "20", "21", "22"] },
  { q: "Who was the prophet who confronted King David about his sin with Bathsheba?", a: 3, opts: ["Samuel", "Elijah", "Isaiah", "Nathan"] },
  { q: "What does 'Emmanuel' mean?", a: 0, opts: ["God with us", "God saves", "God is mighty", "God is love"] },
  { q: "What was the name of Abraham's nephew?", a: 1, opts: ["Ishmael", "Lot", "Nahor", "Terah"] },
  { q: "Who built the first temple in Jerusalem?", a: 2, opts: ["David", "Saul", "Solomon", "Hezekiah"] },
  { q: "What did Elisha ask Elijah for when Elijah was taken up?", a: 3, opts: ["His staff", "His mantle", "His prayers", "A double portion of his spirit"] },
  { q: "Who was the father of Ishmael?", a: 0, opts: ["Abraham", "Isaac", "Jacob", "Nahor"] },
  { q: "Which king was visited by the wise men?", a: 1, opts: ["Caesar Augustus", "Herod", "Pilate", "Agrippa"] },
  { q: "How many tribes of Israel were there?", a: 2, opts: ["10", "11", "12", "13"] },
  { q: "What was the name of the prison where Joseph was held in Egypt?", a: 3, opts: ["The house of Potiphar", "The dungeon of Pharaoh", "The pit of Egypt", "The prison house"] },
  { q: "Which prophet foretold that Jesus would be born in Bethlehem?", a: 0, opts: ["Micah", "Isaiah", "Jeremiah", "Zechariah"] },
  { q: "Who was the first person to see the risen Jesus?", a: 1, opts: ["Peter", "Mary Magdalene", "John", "The two disciples on the road to Emmaus"] },
  { q: "What is the Hebrew word for 'anointed one' (Messiah in English)?", a: 2, opts: ["Adonai", "Elohim", "Mashiach", "Yahweh"] },
  { q: "Who was the mother of Ishmael?", a: 3, opts: ["Sarah", "Keturah", "Rebekah", "Hagar"] },
  { q: "In which city did Jesus raise Lazarus from the dead?", a: 0, opts: ["Bethany", "Bethlehem", "Jerusalem", "Capernaum"] },
  { q: "Who was the Roman centurion whose servant Jesus healed?", a: 1, opts: ["Julius", "Cornelius", "A centurion in Capernaum", "Sergius Paulus"] },
  { q: "Which book records Moses's final speeches to Israel?", a: 2, opts: ["Numbers", "Leviticus", "Deuteronomy", "Joshua"] },
  { q: "Who wrote the book of James?", a: 3, opts: ["James the son of Zebedee", "James the Less", "James the brother of Peter", "James the brother of Jesus"] },
  { q: "What occupation was Paul?", a: 0, opts: ["Tent maker", "Fisherman", "Carpenter", "Tax collector"] },
  { q: "Who was the leader of the 12 spies sent into Canaan?", a: 1, opts: ["Caleb", "Moses", "Joshua", "Aaron"] },

  // --- HARD (~50) ---
  { q: "Who was the mother of King Lemuel, mentioned in Proverbs 31?", a: 2, opts: ["Ruth", "Deborah", "His mother, unnamed", "Bathsheba"] },
  { q: "What was the name of the man who helped carry Jesus's cross?", a: 3, opts: ["Barabbas", "Nicodemus", "Joseph of Arimathea", "Simon of Cyrene"] },
  { q: "Which prophet was called the 'weeping prophet'?", a: 0, opts: ["Jeremiah", "Isaiah", "Ezekiel", "Hosea"] },
  { q: "How many years did the building of Solomon's temple take?", a: 1, opts: ["3", "7", "10", "14"] },
  { q: "Who was the Moabite woman in Jesus's genealogy besides Ruth?", a: 2, opts: ["Rahab", "Bathsheba", "Ruth herself", "Tamar"] },
  { q: "What is the longest chapter in the Bible?", a: 3, opts: ["Psalm 23", "Genesis 1", "Numbers 7", "Psalm 119"] },
  { q: "How many seals are in the book of Revelation?", a: 0, opts: ["7", "6", "8", "12"] },
  { q: "Who was the king of Babylon who besieged Jerusalem?", a: 1, opts: ["Cyrus", "Nebuchadnezzar", "Darius", "Sennacherib"] },
  { q: "Which disciple was a former Zealot?", a: 2, opts: ["Judas Iscariot", "Peter", "Simon the Zealot", "Thaddaeus"] },
  { q: "What was the name of Boaz's closer kinsman-redeemer who refused to marry Ruth?", a: 3, opts: ["Elimelech", "Mahlon", "Chilion", "The name is not given (called 'such a one')"] },
  { q: "Who was the first bishop (elder/overseer) mentioned at Ephesus?", a: 0, opts: ["Timothy", "Titus", "Apollos", "Priscilla"] },
  { q: "Which two books of the Bible do not mention God's name?", a: 1, opts: ["Ruth and Jonah", "Esther and Song of Solomon", "Esther and Ruth", "Song of Solomon and Ecclesiastes"] },
  { q: "How many visions did Zechariah have in one night?", a: 2, opts: ["6", "7", "8", "10"] },
  { q: "Who was Hosea's unfaithful wife?", a: 3, opts: ["Miriam", "Abigail", "Delilah", "Gomer"] },
  { q: "What was the name of Abraham's first homeland city?", a: 0, opts: ["Ur of the Chaldeans", "Haran", "Canaan", "Beersheba"] },
  { q: "Who was the Roman official who heard Paul's defense in Acts 26?", a: 1, opts: ["Felix", "Agrippa", "Festus", "Claudius"] },
  { q: "In what city was the church located that Jesus called 'lukewarm' in Revelation?", a: 2, opts: ["Sardis", "Philadelphia", "Laodicea", "Ephesus"] },
  { q: "Who was Naomi's husband?", a: 3, opts: ["Boaz", "Mahlon", "Chilion", "Elimelech"] },
  { q: "What was the name of the son of Saul who was loyal to David?", a: 0, opts: ["Jonathan", "Ishbosheth", "Abner", "Mephibosheth"] },
  { q: "In which chapter does God speak to Job from the whirlwind?", a: 1, opts: ["Job 37", "Job 38", "Job 40", "Job 42"] },
  { q: "Who was the prophetess who identified the infant Jesus at the temple?", a: 2, opts: ["Miriam", "Deborah", "Anna", "Elizabeth"] },
  { q: "What was the name of the first city Israel conquered in the Promised Land?", a: 3, opts: ["Ai", "Hazor", "Gibeon", "Jericho"] },
  { q: "How many chapters does the book of Leviticus have?", a: 0, opts: ["27", "25", "30", "36"] },
  { q: "Who was the silversmith who stirred up a riot against Paul in Ephesus?", a: 1, opts: ["Alexander", "Demetrius", "Eutychus", "Aristarchus"] },
  { q: "What were the names of Job's three friends?", a: 2, opts: ["Eliphaz, Bildad, and Elihu", "Bildad, Zophar, and Elihu", "Eliphaz, Bildad, and Zophar", "Eliphaz, Elihu, and Zophar"] },
  { q: "In which book is the story of Balaam's donkey?", a: 3, opts: ["Exodus", "Leviticus", "Deuteronomy", "Numbers"] },
  { q: "What were the four rivers that flowed from the Garden of Eden?", a: 0, opts: ["Pishon, Gihon, Hiddekel, Euphrates", "Nile, Jordan, Tigris, Euphrates", "Pishon, Nile, Hiddekel, Gihon", "Tigris, Euphrates, Nile, Jordan"] },
  { q: "Who was the Midianite general killed by Jael?", a: 1, opts: ["Zebah", "Sisera", "Zalmunna", "Oreb"] },
  { q: "What is the name of the high place where Elijah confronted the prophets of Baal?", a: 2, opts: ["Mount Sinai", "Mount Moriah", "Mount Carmel", "Mount Tabor"] },
  { q: "Who succeeded Solomon as king of Israel?", a: 3, opts: ["Abijah", "Asa", "Jehoshaphat", "Rehoboam"] },
  { q: "What does 'Ichabod' mean, the name given when the ark was captured?", a: 0, opts: ["The glory has departed", "God is absent", "The ark is lost", "Israel is defeated"] },
  { q: "How many days did Paul stay in Troas before sailing?", a: 1, opts: ["3", "7", "14", "21"] },
  { q: "Who was the king of Salem to whom Abraham gave tithes?", a: 2, opts: ["Adonizedek", "Bera", "Melchizedek", "Shinab"] },
  { q: "How many horns did the beast from the sea have in Revelation 13?", a: 3, opts: ["7", "8", "9", "10"] },
  { q: "Who was the Ethiopian eunuch reading when Philip approached him?", a: 0, opts: ["Isaiah the prophet", "Jeremiah", "David's Psalms", "Ezekiel"] },
  { q: "What was the name of the disciple Jesus healed of a severed ear?", a: 1, opts: ["The servant of Caiaphas", "Malchus", "Barabbas", "Marcus"] },
  { q: "Which prophet was commanded to lie on his left side for 390 days?", a: 2, opts: ["Hosea", "Zechariah", "Ezekiel", "Jeremiah"] },
  { q: "What was the number of the beast in Revelation?", a: 3, opts: ["616", "444", "999", "666"] },
  { q: "Who was Jephthah's father?", a: 0, opts: ["Gilead", "Manasseh", "Ephraim", "Dan"] },
  { q: "What kind of wood was the ark of Noah made of?", a: 1, opts: ["Cedar", "Gopher wood", "Acacia wood", "Olive wood"] },
  { q: "Who carried the ark of the covenant when Israel crossed the Jordan?", a: 2, opts: ["The soldiers", "The Levites", "The priests", "Joshua"] },
  { q: "In Paul's letter to the Romans, what chapter is the 'love chapter'?", a: 3, opts: ["Romans 5", "Romans 8", "Romans 12", "1 Corinthians 13 (not Romans)"] },
  { q: "What was the name of Abraham's brother who died in Ur?", a: 0, opts: ["Haran", "Nahor", "Terah", "Lot"] },
  { q: "Who anointed Solomon as king?", a: 1, opts: ["Nathan the prophet", "Zadok the priest", "David the king", "Both Zadok and Nathan"] },
  { q: "What is the name of the well Abraham dug that gave the city Beersheba its name?", a: 2, opts: ["En Gedi", "En Rogel", "Beer-lahai-roi", "Well of the oath (Beersheba)"] },
  { q: "Who was the king of Israel when Elijah the prophet began his ministry?", a: 3, opts: ["Jehoshaphat", "Asa", "Omri", "Ahab"] },
  { q: "In which city did Lydia, the seller of purple, live?", a: 0, opts: ["Philippi", "Thyatira", "Corinth", "Ephesus"] },
  { q: "What was the name of Paul's companion on his first missionary journey?", a: 1, opts: ["Silas", "Barnabas", "Timothy", "Luke"] },
  { q: "Who were the parents of John the Baptist?", a: 2, opts: ["Simeon and Anna", "Joseph and Mary", "Zacharias and Elizabeth", "Eli and Hannah"] },
  { q: "What is the name of the sea that Israel crossed into the wilderness?", a: 3, opts: ["The Great Sea", "The Salt Sea", "The Sea of Reeds", "The Red Sea (Yam Suph)"] },
];

export const FILLINS_ALL = [
  // --- GENESIS ---
  { verse: "In the beginning God created the ___ and the earth.", answer: "heaven", ref: "Genesis 1:1", hint: "h_____n" },
  { verse: "And God saw every thing that he had made, and, behold, it was very ___.", answer: "good", ref: "Genesis 1:31", hint: "g__d" },
  { verse: "So God created man in his own ___.", answer: "image", ref: "Genesis 1:27", hint: "i___e" },
  { verse: "The LORD God formed man of the ___ of the ground.", answer: "dust", ref: "Genesis 2:7", hint: "d__t" },
  { verse: "Am I my brother's ___?", answer: "keeper", ref: "Genesis 4:9", hint: "k____r" },
  { verse: "And I will establish my ___ with you.", answer: "covenant", ref: "Genesis 6:18", hint: "c______t" },
  { verse: "The LORD had said unto Abram, Get thee out of thy ___, and from thy kindred.", answer: "country", ref: "Genesis 12:1", hint: "c______y" },
  { verse: "And he believed in the LORD; and he counted it to him for ___.", answer: "righteousness", ref: "Genesis 15:6", hint: "r___________s" },
  { verse: "Is any thing too ___ for the LORD?", answer: "hard", ref: "Genesis 18:14", hint: "h__d" },
  { verse: "The LORD will provide.", answer: "provide", ref: "Genesis 22:14", hint: "p_____e" },

  // --- PSALMS ---
  { verse: "The LORD is my ___; I shall not want.", answer: "shepherd", ref: "Psalm 23:1", hint: "s_______d" },
  { verse: "Yea, though I walk through the valley of the shadow of ___, I will fear no evil.", answer: "death", ref: "Psalm 23:4", hint: "d___h" },
  { verse: "The earth is the LORD's, and the ___ thereof.", answer: "fulness", ref: "Psalm 24:1", hint: "f_____s" },
  { verse: "Create in me a clean ___, O God.", answer: "heart", ref: "Psalm 51:10", hint: "h___t" },
  { verse: "God is our ___ and strength, a very present help in trouble.", answer: "refuge", ref: "Psalm 46:1", hint: "r____e" },
  { verse: "Be still, and know that I am ___.", answer: "God", ref: "Psalm 46:10", hint: "G_d" },
  { verse: "Thy word is a ___ unto my feet, and a light unto my path.", answer: "lamp", ref: "Psalm 119:105", hint: "l__p" },
  { verse: "I will lift up mine eyes unto the ___; from whence cometh my help.", answer: "hills", ref: "Psalm 121:1", hint: "h___s" },
  { verse: "This is the day which the LORD hath made; we will ___ and be glad in it.", answer: "rejoice", ref: "Psalm 118:24", hint: "r_____e" },
  { verse: "The ___ is the beginning of wisdom.", answer: "fear", ref: "Psalm 111:10", hint: "f__r" },
  { verse: "Delight thyself also in the LORD; and he shall give thee the ___ of thine heart.", answer: "desires", ref: "Psalm 37:4", hint: "d_____s" },
  { verse: "Blessed is the man that walketh not in the ___ of the ungodly.", answer: "counsel", ref: "Psalm 1:1", hint: "c_____l" },
  { verse: "The LORD is my light and my ___; whom shall I fear?", answer: "salvation", ref: "Psalm 27:1", hint: "s_______n" },
  { verse: "Cast thy ___ upon the LORD, and he shall sustain thee.", answer: "burden", ref: "Psalm 55:22", hint: "b____n" },

  // --- PROVERBS ---
  { verse: "Trust in the LORD with all thine ___, and lean not unto thine own understanding.", answer: "heart", ref: "Proverbs 3:5", hint: "h___t" },
  { verse: "In all thy ways acknowledge him, and he shall ___ thy paths.", answer: "direct", ref: "Proverbs 3:6", hint: "d____t" },
  { verse: "Train up a ___ in the way he should go.", answer: "child", ref: "Proverbs 22:6", hint: "c____d" },
  { verse: "A ___ friend loveth at all times.", answer: "true", ref: "Proverbs 17:17", hint: "t__e" },
  { verse: "Pride goeth before ___, and an haughty spirit before a fall.", answer: "destruction", ref: "Proverbs 16:18", hint: "d_________n" },
  { verse: "A soft ___ turneth away wrath.", answer: "answer", ref: "Proverbs 15:1", hint: "a_____r" },
  { verse: "Where there is no ___, the people perish.", answer: "vision", ref: "Proverbs 29:18", hint: "v____n" },
  { verse: "The heart of man ___ his way: but the LORD directeth his steps.", answer: "deviseth", ref: "Proverbs 16:9", hint: "d______h" },

  // --- ISAIAH ---
  { verse: "But they that wait upon the LORD shall renew their ___.", answer: "strength", ref: "Isaiah 40:31", hint: "s________h" },
  { verse: "Fear thou not; for I am with thee: be not dismayed; for I am thy ___.", answer: "God", ref: "Isaiah 41:10", hint: "G_d" },
  { verse: "For unto us a ___ is born, unto us a son is given.", answer: "child", ref: "Isaiah 9:6", hint: "c____d" },
  { verse: "He was wounded for our ___, he was bruised for our iniquities.", answer: "transgressions", ref: "Isaiah 53:5", hint: "t____________s" },
  { verse: "Come now, and let us reason together, saith the LORD: though your sins be as ___, they shall be as white as snow.", answer: "scarlet", ref: "Isaiah 1:18", hint: "s_____t" },
  { verse: "Thou wilt keep him in perfect ___, whose mind is stayed on thee.", answer: "peace", ref: "Isaiah 26:3", hint: "p___e" },
  { verse: "And thine ears shall hear a word behind thee, saying, This is the ___, walk ye in it.", answer: "way", ref: "Isaiah 30:21", hint: "w_y" },

  // --- JEREMIAH ---
  { verse: "For I know the ___ that I think toward you, saith the LORD.", answer: "thoughts", ref: "Jeremiah 29:11", hint: "t______s" },
  { verse: "The heart is ___ above all things, and desperately wicked.", answer: "deceitful", ref: "Jeremiah 17:9", hint: "d_______l" },
  { verse: "Call unto me, and I will ___ thee, and shew thee great and mighty things.", answer: "answer", ref: "Jeremiah 33:3", hint: "a_____r" },
  { verse: "Is there no balm in ___; is there no physician there?", answer: "Gilead", ref: "Jeremiah 8:22", hint: "G____d" },

  // --- LAMENTATIONS ---
  { verse: "It is of the LORD's ___ that we are not consumed.", answer: "mercies", ref: "Lamentations 3:22", hint: "m_____s" },
  { verse: "Great is thy ___.", answer: "faithfulness", ref: "Lamentations 3:23", hint: "f__________s" },

  // --- MATTHEW ---
  { verse: "Blessed are the ___ in spirit: for theirs is the kingdom of heaven.", answer: "poor", ref: "Matthew 5:3", hint: "p__r" },
  { verse: "Blessed are the ___: for they shall inherit the earth.", answer: "meek", ref: "Matthew 5:5", hint: "m__k" },
  { verse: "Ye are the ___ of the world.", answer: "light", ref: "Matthew 5:14", hint: "l___t" },
  { verse: "But seek ye first the ___ of God, and his righteousness.", answer: "kingdom", ref: "Matthew 6:33", hint: "k_____m" },
  { verse: "Ask, and it shall be given you; ___, and ye shall find.", answer: "seek", ref: "Matthew 7:7", hint: "s__k" },
  { verse: "Come unto me, all ye that labour and are heavy laden, and I will give you ___.", answer: "rest", ref: "Matthew 11:28", hint: "r__t" },
  { verse: "For God so ___ the world, that he gave his only begotten Son.", answer: "loved", ref: "John 3:16", hint: "l___d" },
  { verse: "With ___ nothing shall be impossible.", answer: "God", ref: "Matthew 19:26", hint: "G_d" },
  { verse: "Go ye therefore, and ___ all nations.", answer: "teach", ref: "Matthew 28:19", hint: "t___h" },
  { verse: "And lo, I am with you alway, even unto the end of the ___.", answer: "world", ref: "Matthew 28:20", hint: "w____d" },

  // --- MARK ---
  { verse: "The time is fulfilled, and the ___ of God is at hand: repent ye, and believe the gospel.", answer: "kingdom", ref: "Mark 1:15", hint: "k_____m" },
  { verse: "And he said unto them, Go ye into all the world, and preach the ___ to every creature.", answer: "gospel", ref: "Mark 16:15", hint: "g____l" },
  { verse: "With men it is ___, but not with God: for with God all things are possible.", answer: "impossible", ref: "Mark 10:27", hint: "i_________e" },

  // --- LUKE ---
  { verse: "For with God nothing shall be impossible.", answer: "impossible", ref: "Luke 1:37", hint: "i_________e" },
  { verse: "For the Son of man is come to seek and to ___ that which was lost.", answer: "save", ref: "Luke 19:10", hint: "s__e" },
  { verse: "And the ___ shall return to the dust as it was: and the spirit shall return unto God who gave it.", answer: "body", ref: "Ecclesiastes 12:7", hint: "b__y" },
  { verse: "Father, forgive them; for they know not what they ___.", answer: "do", ref: "Luke 23:34", hint: "d_" },
  { verse: "Blessed are you among ___, and blessed is the fruit of your womb.", answer: "women", ref: "Luke 1:42", hint: "w____n" },

  // --- JOHN ---
  { verse: "In the beginning was the ___, and the Word was with God.", answer: "Word", ref: "John 1:1", hint: "W__d" },
  { verse: "And the Word was made ___, and dwelt among us.", answer: "flesh", ref: "John 1:14", hint: "f____h" },
  { verse: "Jesus saith unto him, I am the way, the ___, and the life.", answer: "truth", ref: "John 14:6", hint: "t___h" },
  { verse: "The thief cometh not, but for to steal, and to kill, and to destroy: I am come that they might have ___, and that they might have it more abundantly.", answer: "life", ref: "John 10:10", hint: "l__e" },
  { verse: "Jesus ___.", answer: "wept", ref: "John 11:35", hint: "w__t" },
  { verse: "Peace I leave with you, my ___ I give unto you.", answer: "peace", ref: "John 14:27", hint: "p___e" },
  { verse: "I am the ___ and the life: he that believeth in me, though he were dead, yet shall he live.", answer: "resurrection", ref: "John 11:25", hint: "r__________n" },
  { verse: "Greater ___ hath no man than this, that a man lay down his life for his friends.", answer: "love", ref: "John 15:13", hint: "l__e" },
  { verse: "And ye shall know the ___, and the truth shall make you free.", answer: "truth", ref: "John 8:32", hint: "t___h" },
  { verse: "I am the good ___: the good shepherd giveth his life for the sheep.", answer: "shepherd", ref: "John 10:11", hint: "s_______d" },

  // --- ACTS ---
  { verse: "But ye shall receive ___, after that the Holy Ghost is come upon you.", answer: "power", ref: "Acts 1:8", hint: "p___r" },
  { verse: "Neither is there ___ in any other: for there is none other name under heaven given among men, whereby we must be saved.", answer: "salvation", ref: "Acts 4:12", hint: "s_______n" },
  { verse: "We ought to obey ___ rather than men.", answer: "God", ref: "Acts 5:29", hint: "G_d" },
  { verse: "Believe on the Lord Jesus Christ, and thou shalt be ___, and thy house.", answer: "saved", ref: "Acts 16:31", hint: "s___d" },

  // --- ROMANS ---
  { verse: "For all have ___, and come short of the glory of God.", answer: "sinned", ref: "Romans 3:23", hint: "s____d" },
  { verse: "For the wages of sin is ___; but the gift of God is eternal life.", answer: "death", ref: "Romans 6:23", hint: "d___h" },
  { verse: "And we know that all things work together for ___ to them that love God.", answer: "good", ref: "Romans 8:28", hint: "g__d" },
  { verse: "I am persuaded, that neither death, nor life... shall be able to separate us from the ___ of God.", answer: "love", ref: "Romans 8:38-39", hint: "l__e" },
  { verse: "For I am not ___ of the gospel of Christ: for it is the power of God unto salvation.", answer: "ashamed", ref: "Romans 1:16", hint: "a_____d" },
  { verse: "Present your bodies a living ___, holy, acceptable unto God.", answer: "sacrifice", ref: "Romans 12:1", hint: "s_______e" },
  { verse: "Be not conformed to this world: but be ye ___ by the renewing of your mind.", answer: "transformed", ref: "Romans 12:2", hint: "t__________d" },
  { verse: "If God be for us, who can be ___ us?", answer: "against", ref: "Romans 8:31", hint: "a_____t" },

  // --- 1 CORINTHIANS ---
  { verse: "Though I speak with the tongues of men and of angels, and have not ___, I am become as sounding brass.", answer: "charity", ref: "1 Corinthians 13:1", hint: "c_____y" },
  { verse: "___ suffereth long, and is kind.", answer: "Charity", ref: "1 Corinthians 13:4", hint: "C_____y" },
  { verse: "And now abideth faith, hope, charity, these three; but the greatest of these is ___.", answer: "charity", ref: "1 Corinthians 13:13", hint: "c_____y" },
  { verse: "O ___, where is thy sting? O grave, where is thy victory?", answer: "death", ref: "1 Corinthians 15:55", hint: "d___h" },
  { verse: "Be strong in the Lord, and in the power of his ___.", answer: "might", ref: "Ephesians 6:10", hint: "m___t" },
  { verse: "For the preaching of the cross is to them that perish ___; but unto us which are saved it is the power of God.", answer: "foolishness", ref: "1 Corinthians 1:18", hint: "f_________s" },
  { verse: "Know ye not that your body is the ___ of the Holy Ghost which is in you?", answer: "temple", ref: "1 Corinthians 6:19", hint: "t____e" },

  // --- GALATIANS ---
  { verse: "But the ___ of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith.", answer: "fruit", ref: "Galatians 5:22", hint: "f___t" },
  { verse: "Be not deceived; God is not ___: for whatsoever a man soweth, that shall he also reap.", answer: "mocked", ref: "Galatians 6:7", hint: "m____d" },
  { verse: "I am ___ with Christ: nevertheless I live; yet not I, but Christ liveth in me.", answer: "crucified", ref: "Galatians 2:20", hint: "c_______d" },

  // --- EPHESIANS ---
  { verse: "For by ___ are ye saved through faith.", answer: "grace", ref: "Ephesians 2:8", hint: "g___e" },
  { verse: "And be ye ___ one to another, tenderhearted, forgiving one another.", answer: "kind", ref: "Ephesians 4:32", hint: "k__d" },
  { verse: "Put on the whole ___ of God, that ye may be able to stand against the wiles of the devil.", answer: "armour", ref: "Ephesians 6:11", hint: "a_____r" },
  { verse: "Children, ___ your parents in the Lord: for this is right.", answer: "obey", ref: "Ephesians 6:1", hint: "o__y" },

  // --- PHILIPPIANS ---
  { verse: "I can do all things through ___ which strengtheneth me.", answer: "Christ", ref: "Philippians 4:13", hint: "C____t" },
  { verse: "And the ___ of God, which passeth all understanding, shall keep your hearts and minds.", answer: "peace", ref: "Philippians 4:7", hint: "p___e" },
  { verse: "Rejoice in the Lord alway: and again I say, ___.", answer: "Rejoice", ref: "Philippians 4:4", hint: "R_____e" },
  { verse: "Let your ___ be known unto all men.", answer: "moderation", ref: "Philippians 4:5", hint: "m_________n" },

  // --- COLOSSIANS ---
  { verse: "Set your ___ on things above, not on things on the earth.", answer: "affection", ref: "Colossians 3:2", hint: "a________n" },
  { verse: "And whatsoever ye do, do it heartily, as to the ___, and not unto men.", answer: "Lord", ref: "Colossians 3:23", hint: "L__d" },
  { verse: "Let the ___ of Christ dwell in you richly.", answer: "word", ref: "Colossians 3:16", hint: "w__d" },

  // --- 1 THESSALONIANS ---
  { verse: "Pray without ___.", answer: "ceasing", ref: "1 Thessalonians 5:17", hint: "c_____g" },
  { verse: "In every thing give ___: for this is the will of God in Christ Jesus concerning you.", answer: "thanks", ref: "1 Thessalonians 5:18", hint: "t____s" },
  { verse: "Prove all things; hold fast that which is ___.", answer: "good", ref: "1 Thessalonians 5:21", hint: "g__d" },

  // --- 1 TIMOTHY ---
  { verse: "For the love of ___ is the root of all evil.", answer: "money", ref: "1 Timothy 6:10", hint: "m___y" },
  { verse: "Godliness with ___ is great gain.", answer: "contentment", ref: "1 Timothy 6:6", hint: "c_________t" },
  { verse: "Fight the good fight of ___.", answer: "faith", ref: "1 Timothy 6:12", hint: "f___h" },

  // --- HEBREWS ---
  { verse: "Now ___ is the substance of things hoped for, the evidence of things not seen.", answer: "faith", ref: "Hebrews 11:1", hint: "f___h" },
  { verse: "Let us run with patience the ___ that is set before us.", answer: "race", ref: "Hebrews 12:1", hint: "r__e" },
  { verse: "Jesus Christ the same yesterday, and to day, and for ___.", answer: "ever", ref: "Hebrews 13:8", hint: "e__r" },
  { verse: "Be content with such things as ye have: for he hath said, I will never leave thee, nor ___ thee.", answer: "forsake", ref: "Hebrews 13:5", hint: "f_____e" },
  { verse: "For the word of God is quick, and ___, and sharper than any twoedged sword.", answer: "powerful", ref: "Hebrews 4:12", hint: "p______l" },
  { verse: "And without ___ it is impossible to please him.", answer: "faith", ref: "Hebrews 11:6", hint: "f___h" },

  // --- JAMES ---
  { verse: "Draw nigh to ___, and he will draw nigh to you.", answer: "God", ref: "James 4:8", hint: "G_d" },
  { verse: "If any of you lack ___, let him ask of God.", answer: "wisdom", ref: "James 1:5", hint: "w_____m" },
  { verse: "Even so ___, if it hath not works, is dead.", answer: "faith", ref: "James 2:17", hint: "f___h" },
  { verse: "Resist the devil, and he will ___ from you.", answer: "flee", ref: "James 4:7", hint: "f__e" },
  { verse: "The effectual fervent prayer of a righteous man availeth ___.", answer: "much", ref: "James 5:16", hint: "m__h" },

  // --- 1 PETER ---
  { verse: "Casting all your ___ upon him; for he careth for you.", answer: "care", ref: "1 Peter 5:7", hint: "c__e" },
  { verse: "Be sober, be vigilant; because your adversary the devil, as a roaring ___, walketh about.", answer: "lion", ref: "1 Peter 5:8", hint: "l__n" },
  { verse: "But ye are a chosen ___, a royal priesthood, an holy nation.", answer: "generation", ref: "1 Peter 2:9", hint: "g_________n" },
  { verse: "For all flesh is as grass, and all the glory of man as the flower of ___.", answer: "grass", ref: "1 Peter 1:24", hint: "g___s" },

  // --- 1 JOHN ---
  { verse: "God is ___, and he that dwelleth in love dwelleth in God.", answer: "love", ref: "1 John 4:16", hint: "l__e" },
  { verse: "If we confess our sins, he is faithful and just to ___ us our sins.", answer: "forgive", ref: "1 John 1:9", hint: "f_____e" },
  { verse: "For whatsoever is born of God overcometh the world: and this is the victory that overcometh the world, even our ___.", answer: "faith", ref: "1 John 5:4", hint: "f___h" },
  { verse: "Beloved, let us ___ one another: for love is of God.", answer: "love", ref: "1 John 4:7", hint: "l__e" },
  { verse: "We ___ him, because he first loved us.", answer: "love", ref: "1 John 4:19", hint: "l__e" },

  // --- REVELATION ---
  { verse: "I am ___ and Omega, the beginning and the ending, saith the Lord.", answer: "Alpha", ref: "Revelation 1:8", hint: "A____a" },
  { verse: "Behold, I stand at the door, and ___: if any man hear my voice, and open the door, I will come in to him.", answer: "knock", ref: "Revelation 3:20", hint: "k___k" },
  { verse: "And God shall wipe away all ___ from their eyes.", answer: "tears", ref: "Revelation 21:4", hint: "t___s" },
  { verse: "And there shall be no more ___: neither sorrow, nor crying.", answer: "death", ref: "Revelation 21:4", hint: "d___h" },
  { verse: "He that overcometh shall inherit all things; and I will be his ___, and he shall be my son.", answer: "God", ref: "Revelation 21:7", hint: "G_d" },
  { verse: "And the Spirit and the bride say, Come. And let him that heareth say, ___.", answer: "Come", ref: "Revelation 22:17", hint: "C__e" },
  { verse: "And, behold, I come quickly; and my ___ is with me, to give every man according as his work shall be.", answer: "reward", ref: "Revelation 22:12", hint: "r____d" },
  { verse: "Blessed are they that do his ___, that they may have right to the tree of life.", answer: "commandments", ref: "Revelation 22:14", hint: "c___________s" },

  // --- ADDITIONAL MIXED VERSES ---
  { verse: "And Moses said unto God, Who am I, that I should go unto ___?", answer: "Pharaoh", ref: "Exodus 3:11", hint: "P_____h" },
  { verse: "The LORD bless thee, and keep thee.", answer: "keep", ref: "Numbers 6:24", hint: "k__p" },
  { verse: "Be strong and of a good ___; be not afraid.", answer: "courage", ref: "Joshua 1:9", hint: "c_____e" },
  { verse: "Choose you this day whom ye will ___.", answer: "serve", ref: "Joshua 24:15", hint: "s__ve" },
  { verse: "The LORD is my ___ and my shield; my heart trusted in him.", answer: "strength", ref: "Psalm 28:7", hint: "s________h" },
  { verse: "How amiable are thy ___, O LORD of hosts!", answer: "tabernacles", ref: "Psalm 84:1", hint: "t__________s" },
  { verse: "O give thanks unto the LORD; for he is good: for his ___ endureth for ever.", answer: "mercy", ref: "Psalm 136:1", hint: "m___y" },
  { verse: "Search me, O God, and know my ___.", answer: "heart", ref: "Psalm 139:23", hint: "h___t" },
  { verse: "The fear of the LORD is the beginning of ___: a good understanding have all they that do his commandments.", answer: "wisdom", ref: "Psalm 111:10", hint: "w_____m" },
  { verse: "He healeth the broken in heart, and bindeth up their ___.", answer: "wounds", ref: "Psalm 147:3", hint: "w____s" },
  { verse: "Honour thy ___ and thy mother: that thy days may be long.", answer: "father", ref: "Exodus 20:12", hint: "f____r" },
  { verse: "Thou shalt love the LORD thy God with all thine ___, and with all thy soul.", answer: "heart", ref: "Deuteronomy 6:5", hint: "h___t" },
  { verse: "And she brought forth her firstborn son, and wrapped him in swaddling ___, and laid him in a manger.", answer: "clothes", ref: "Luke 2:7", hint: "c_____s" },
  { verse: "For unto you is born this day in the city of David a ___, which is Christ the Lord.", answer: "Saviour", ref: "Luke 2:11", hint: "S_____r" },
  { verse: "My ___ and my God.", answer: "Lord", ref: "John 20:28", hint: "L__d" },
  { verse: "For to me to live is ___, and to die is gain.", answer: "Christ", ref: "Philippians 1:21", hint: "C____t" },
  { verse: "I have learned, in whatsoever state I am, therewith to be ___.", answer: "content", ref: "Philippians 4:11", hint: "c_____t" },
  { verse: "Now the God of ___ fill you with all joy and peace in believing.", answer: "hope", ref: "Romans 15:13", hint: "h__e" },
  { verse: "For I reckon that the sufferings of this present time are not worthy to be compared with the ___ which shall be revealed in us.", answer: "glory", ref: "Romans 8:18", hint: "g___y" },
  { verse: "No ___ is common to man: but God is faithful, who will not suffer you to be tempted above that ye are able.", answer: "temptation", ref: "1 Corinthians 10:13", hint: "t_________n" },
  { verse: "Thanks be unto God for his ___ gift.", answer: "unspeakable", ref: "2 Corinthians 9:15", hint: "u_________e" },
  { verse: "My grace is sufficient for thee: for my ___ is made perfect in weakness.", answer: "strength", ref: "2 Corinthians 12:9", hint: "s________h" },
  { verse: "Whatsoever things are true... think on these ___.", answer: "things", ref: "Philippians 4:8", hint: "t_____s" },
  { verse: "For God hath not given us the spirit of ___; but of power, and of love, and of a sound mind.", answer: "fear", ref: "2 Timothy 1:7", hint: "f__r" },
  { verse: "All scripture is given by ___ of God.", answer: "inspiration", ref: "2 Timothy 3:16", hint: "i_________n" },
  { verse: "I have fought a good fight, I have finished my ___, I have kept the faith.", answer: "course", ref: "2 Timothy 4:7", hint: "c_____e" },
];
